#! /bin/sh
#
# qucsdigi - wrapper script for digital simulation
#
# Copyright (C) 2005 Michael Margraf <michael.margraf@alumni.tu-berlin.de>
# Copyright (C) 2005 Stefan Jahn <stefan@lkcc.org>
# Copyright (C) 2005 Raimund Jacob <raimi@lkcc.org>
#
# This is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
# 
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this package; see the file COPYING.  If not, write to
# the Free Software Foundation, Inc., 51 Franklin Street - Fifth Floor,
# Boston, MA 02110-1301, USA.  
#

# Bail out on any error
set -e

if [ "$#" != 3 ]; then
    echo "Usage: $0 <netlist.txt> <time> <directory>"
    echo " Directory has to contain netlist.txt"
    exit 1
fi

NAME=$1
TIME=$2
DIR=$3

if [ ! -d "$DIR" ]; then
    echo "$DIR: Not a directory"
    exit 1
fi

cd $DIR

if [ ! -f $NAME ]; then
    echo "$NAME: No such file"
    exit 1
fi

CXX=`freehdl-config --cxx`
CXXFLAGS=`freehdl-config --cxxflags`
LIBS=`freehdl-config --libtool`
LDFLAGS=`freehdl-config --ldflags`

cp $NAME digi.vhdl
NAME="digi"

echo -n "running C++ conversion..."
# FIXME: Isn't this diverting important output in the error case ?
# freehdl-v2cc -m $NAME._main_.cc -o $NAME.cc $NAME.vhdl 2>/dev/null
freehdl-v2cc -m $NAME._main_.cc -o $NAME.cc $NAME.vhdl
echo " done."

echo -n "compiling functions..."
$CXX $CXXFLAGS -c $NAME.cc
echo " done."

echo -n "compiling main..."
$CXX $CXXFLAGS -c $NAME._main_.cc
echo " done."

echo -n "linking..."
freehdl-libtool --quiet --mode=link $CXX $NAME._main_.o $NAME.o $LIBS -o $NAME
echo " done."

echo -n "simulating..."
./$NAME -cmd "dc -f $NAME.vcd -q;d;run $TIME;q;" >/dev/null
echo " done."

echo -n "running VCD conversion..."
#qucsconv -if vcd -of qucsdata -i $NAME.vcd -o $NAME.dat
echo " done."
