.TH QucsEdit "1" "September 2004" "Debian/GNU Linux" "User Commands"
.SH NAME
QucsEdit \- A simple text editor for Qucs.
.SH SYNOPSIS
.B qucsedit
[\fIOPTION\fR] \fIfile\fR ...
.SH DESCRIPTION

\fBQucs\fR is an integrated circuit simulator which means you are able
to setup a circuit with a graphical user interface (GUI) and simulate
the large-signal, small-signal and noise behaviour of the circuit.
After that simulation has finished you can view the simulation results
on a presentation page or window.

The software aims to support all kinds of circuit simulation types,
e.g. DC, AC, S-parameter, harmonic balance analysis, noise analysis,
etc.

\fBQucsEdit\fR is a simple text editor used by Qucs.

.SH OPTIONS
.TP
\fB\-h\fR
display this help and exit
.TP
\fB\-r\fR FILENAME
open file read-only
.SH AVAILABILITY
The latest version of Qucs can always be obtained from
\fBwww.sourceforge.net\fR or \fBwww.freshmeat.net\fR
.SH "REPORTING BUGS"
Known bugs are documented within the BUGS file.  Report bugs to
<qucs-bugs@lists.sourceforge.net>.
.SH COPYRIGHT
Copyright \(co 2004, 2005 Michael Margraf <michael.margraf@alumni.tu-berlin.de>
.PP
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH AUTHORS
Written by Michael Margraf <michael.margraf@alumni.tu-berlin.de> and
Stefan Jahn <stefan@lkcc.org>.
