#!/bin/bash

QUCS=../main/qucs
out=out
ref=${srcdir}/ref

base=$( basename $1 )
eval echo $base ${REDIR}
eval echo "$@" ${REDIR}

# eval echo $( cd ${srcdir}; ls $base/*.sch ) ${REDIR}
# eval echo ${srcdir}/$base ${REDIR}

mkdir ${out}

for i in $( cd ${srcdir}; ls $base/*.sch ) ; do
	schname=$(basename $i)
	eval echo more $base $schname ${REDIR}

	# dump qucsator netlist
	rm -f "${out}/${base}_${schname}.net"
	cmd="$QUCS -n -i ${srcdir}/$i -o ${out}/${base}_${schname}.net"
	eval echo "$cmd" ${REDIR}
	eval "$cmd" ${REDIR}

	# BUG: use stdout and filter
	sed -i '1 s/Qucs.*/Qucs/' ${out}/${base}_${schname}.net

	# dump verilog netlist
	rm -f "${out}/${base}_${schname}.v"
	cmd="$QUCS -a ../qucs/sim/.libs/verilog.so -l verilog_nl -n -i ${srcdir}/$i -o ${out}/${base}_${schname}.v"
	eval echo "$cmd" ${REDIR}
	eval "$cmd" ${REDIR}
	
	# dump legacy schematic
	rm -f "${out}/${base}_${schname}.dup"
	cmd="$QUCS -l leg_sch -n -i ${srcdir}/$i -o ${out}/${base}_${schname}.dup"
	eval echo "$cmd" ${REDIR}
	eval "$cmd" ${REDIR}

	# dump verilog schematic
	rm -f "${out}/${base}_${schname}.vs"
	cmd="$QUCS -a ../qucs/sim/.libs/verilog.so -l v_sch -n -i ${srcdir}/$i -o ${out}/${base}_${schname}.vs"
	eval echo "$cmd" ${REDIR}
	eval "$cmd" ${REDIR}

	# =================================
	status=PASS

	files="${base}_${schname}.net ${base}_${schname}.dup ${base}_${schname}.vs ${base}_${schname}.v"

	for F in $files; do
		cmd="diff ${out}/${F} ${ref}/${F}"
		eval echo "$cmd" ${REDIR}
		eval "$cmd" ${REDIR}
		if [ $? -ne 0 ]; then status=FAIL; fi
	done

	if [ $status = FAIL ]; then
		exit 1
	fi

done

