
#TODO: relation to common.mk??

QUCS_LIB_INCLUDE = -I$(top_srcdir)/qucs-lib
AM_CPPFLAGS = $(X11_INCLUDES) $(QT_CFLAGS) -I$(top_srcdir)/qucs \
              ${QUCS_LIB_INCLUDE}

CXX_STD = "-std=c++14"
AM_CXXFLAGS = ${CXX_STD}
