#!/bin/bash

QUCS=../qucs/qucs # BUG
out=out
ref=${srcdir}/ref
DIFF=diff\ -rup
VERILOG_PLUGIN=../plugins/verilog/.libs/verilog

base=$( basename $1 )
eval echo $base ${REDIR}
eval echo "$@" ${REDIR}

# eval echo $( cd ${srcdir}; ls $base/*.sch ) ${REDIR}
# eval echo ${srcdir}/$base ${REDIR}

mkdir ${out}

status=PASS

# TODO: cleanup. explicit any to any
for i in $( cd ${srcdir}; ls $base/*.{sch,vs} ) ; do
	schname=$(basename $i)
	eval echo more $base $schname ${REDIR}

	# dump qucsator netlist
	rm -f "${out}/${base}_${schname}.net"
	cmd="$QUCS -n -i ${srcdir}/$i -o ${out}/${base}_${schname}.net -platform offscreen"
	eval echo "$cmd" ${REDIR}
	eval "$cmd" ${REDIR}

	# BUG: use stdout and filter
	sed -i '1 s/Qucs.*/Qucs/' ${out}/${base}_${schname}.net

# not yet
### 	# dump verilog netlist
### 	rm -f "${out}/${base}_${schname}.v"
### 	cmd="$QUCS -a $VERILOG_PLUGIN -l verilog_nl -n -i ${srcdir}/$i -o ${out}/${base}_${schname}.v"
### 	eval echo "$cmd" ${REDIR}
### 	eval "$cmd" ${REDIR}
### 
### 	# BUG: use stdout and filter
### 	sed -i '1 s/Qucs.*/Qucs/' ${out}/${base}_${schname}.v
### 	
	# dump legacy schematic
	rm -f "${out}/${base}_${schname}.sch"
	cmd="$QUCS -i ${srcdir}/$i --dump -o ${out}/${base}_${schname}.sch -platform offscreen"
	eval echo "$cmd" ${REDIR}
	eval "$cmd" ${REDIR}

	# dump verilog schematic
	rm -f "${out}/${base}_${schname}.vs"
	cmd="$QUCS -i ${srcdir}/$i --dump -t vs -o ${out}/${base}_${schname}.vs -platform offscreen"
	eval echo "$cmd" ${REDIR}

	# BUG. need flag to specify user error output file.
	# cmd+="-d ${out}/${base}_${schname}.vs.tmp"
	# (ab)using stdout for now, hardwired, see Schematic::warn..
	eval "$cmd > ${out}/${base}_${schname}.vs.tmp" ${REDIR}

	# TODO: explicit, use a macro maybe
	case $i in
	*.vs)
		$DIFF ${srcdir}/$i ${out}/${base}_${schname%%.vs}.sch.vs >> roundtrip_vs.diff
		;;
	*.sch)
		$DIFF ${srcdir}/$i ${out}/${base}_${schname%%.sch}.vs.sch >> roundtrip_sch.diff
		;;
	esac

	# .tmp ist part of what is tested, append it
	cat ${out}/${base}_${schname}.vs.tmp >> ${out}/${base}_${schname}.vs
	rm ${out}/${base}_${schname}.vs.tmp

	# =================================

	files="${base}_${schname}.net ${base}_${schname}.sch ${base}_${schname}.vs" # later " ${base}_${schname}.v"

	for F in $files; do
		cmd="$DIFF ${out}/${F} ${ref}/${F}"
		eval echo "$cmd" ${REDIR}
		eval "$cmd" ${REDIR}
		if [ $? -ne 0 ]; then
			echo "ERROR $F"
			status=FAIL;
		fi
	done

done

if [ $status = FAIL ]; then
	exit 1
fi
