#! /bin/bash

export AR=i586-mingw32msvc-ar
export AS=i586-mingw32msvc-as
export CXX=i586-mingw32msvc-c++
export CC=i586-mingw32msvc-gcc
export LD=i586-mingw32msvc-ld
export DLLTOOL=i586-mingw32msvc-dlltool
export NM=i586-mingw32msvc-nm
export OBJDUMP=i586-mingw32msvc-objdump
export RANLIB=i586-mingw32msvc-ranlib
export STRIP=i586-mingw32msvc-strip
export WINDRES=i586-mingw32msvc-windres

echo "Configuring for i386-MinGW32 cross ..."
./configure $* --target=i386-mingw32 --host=i386-mingw32 --build=i586-linux --program-prefix=""
