#! /bin/sh
#
# qucsveri - wrapper script for digital simulation
#
# Copyright (C) 2007 Stefan Jahn <stefan@lkcc.org>
#
# This is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
# 
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this package; see the file COPYING.  If not, write to
# the Free Software Foundation, Inc., 51 Franklin Street - Fifth Floor,
# Boston, MA 02110-1301, USA.  
#

# Bail out on any error
set -e

# catch termination signal and kill all child processes
#trap 'kill 0; exit 0' SIGTERM

if [ "$#" != 5 ]; then
    if [ "$#" != 6 ]; then
        echo "Usage: $0 <netlist.txt> <output.dat> <time> <directory> <bindirectory> [<convoption>]"
        echo "Directory has to contain the file 'netlist.txt'."
        exit 1
    fi
    OPTION=$6
fi

NAME=$1
NAMEOUT=$2
TIME=$3
DIR=$4
BINDIR=$5

if [ ! -d "$DIR" ]; then
    echo "$DIR: Not a directory"
    exit 1
fi

cd $DIR

if [ ! -f $NAME ]; then
    echo "$NAME: No such file"
    exit 1
fi

cp $NAME digi.v
NAME="digi"

echo -n "running VerilogHDL conversion..."
iverilog -o$NAME -sTestBench $NAME.v
echo " done."

echo "simulating..."
vvp $NAME -vcd
wait $!

echo -n "running VCD conversion..."
$BINDIR/qucsconv $OPTION -if vcd -of qucsdata -i $NAME.vcd -o "$NAMEOUT"
echo " done."
