/* File automatically created by ./mkctext.pl*/

const char * adms_implicit_xml = ""
"<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n"
"<!-- built-in implicit transforms @SVN_VERSION=1228:1229M@ -->\n"
"<!-- this file is saved in local working directory, then downloaded prior any -e xml files -->\n"
"<!-- unless flag '-x' is specified -->\n"
"\n"
"<!DOCTYPE admst SYSTEM \"admst.dtd\">\n"
"<admst version=\"2.3.0\" xmlns:admst=\"http://mot-adms.sourceforge.net/adms/admst.xml\">\n"
"\n"
"<admst:variable name=\"globalmodule\"/>\n"
"<admst:variable name=\"globalassignment\"/>\n"
"<admst:variable name=\"globalcontribution\"/>\n"
"<admst:variable name=\"globalexpression\"/>\n"
"<admst:variable name=\"globalopdependent\" string=\"no\"/>\n"
"<admst:variable name=\"globalpartitionning\"/>\n"
"<admst:variable name=\"globaltreenode\"/>\n"
"\n"
"<admst:template match=\"e:init\">\n"
"  <admst:choose>\n"
"    <admst:when test=\"[datatypename='expression']\">\n"
"      <admst:variable name=\"globalexpression\" path=\".\"/>\n"
"      <admst:apply-templates select=\"tree\" match=\"e:init\"/>\n"
"      <admst:variable name=\"globalexpression\"/>\n"
"      <admst:reverse select=\"function\"/>\n"
"      <admst:value-to select=\"math/value\" path=\"tree/math/value\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='probe']\">\n"
"      <admst:push into=\"$globalexpression/probe\" select=\".\" onduplicate=\"ignore\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='array']\">\n"
"      <admst:apply-templates select=\"variable\" match=\"e:init\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='variable']\">\n"
"      <admst:push into=\"$globalexpression/variable\" select=\".\" onduplicate=\"ignore\"/>\n"
"      <admst:push into=\"$globaltreenode/@variable\" select=\".\" onduplicate=\"ignore\"/>\n"
"      <admst:push into=\"$globalexpression/probe\" select=\"probe\" onduplicate=\"ignore\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='mapply_unary']\">\n"
"      <admst:apply-templates select=\"arg1\" match=\"e:init\"/>\n"
"      <admst:value-to select=\"[name='minus']/math/value\" string=\"-%(arg1/math/value)\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='mapply_binary']\">\n"
"      <admst:apply-templates select=\"arg1|arg2\" match=\"e:init\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='mapply_ternary']\">\n"
"      <admst:apply-templates select=\"arg1|arg2|arg3\" match=\"e:init\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='function']\">\n"
"      <admst:choose>\n"
"        <admst:when test=\"[name='ddx' or name='\\$ddx' or name='\\$derivate']\">\n"
"          <admst:value-to select=\"$globalassignment/lhs/derivate\" string=\"yes\"/>\n"
"          <admst:apply-templates select=\"arguments[1]\" match=\"e:init\"/>\n"
"          <admst:push into=\"$globalexpression/variable/ddxprobe\" select=\"arguments[2]\" onduplicate=\"ignore\"/>\n"
"        </admst:when>\n"
"        <admst:otherwise>\n"
"          <admst:apply-templates select=\"arguments\" match=\"e:init\"/>\n"
"        </admst:otherwise>\n"
"      </admst:choose>\n"
"      <admst:choose>\n"
"        <admst:when test=\"[name='\\$realtime' or name='\\$temperature' or name='\\$vt' or name='idt' or name='ddt' or\n"
"                           name='\\$param_given' or name='\\$given' or name='ddx' or name='flicker_noise' or name='white_noise']\"/>\n"
"        <!--Trigonometric and hyperbolic functions-->\n"
"        <admst:when\n"
"          test=\"[\n"
"            name='sin' or name='cos' or name='tan' or name='asin' or name='acos' or name='atan' or\n"
"            name='atan2' or name='hypot' or\n"
"            name='sinh' or name='cosh' or name='tanh' or name='asinh' or name='acosh' or name='atanh'\n"
"          ]\">\n"
"          <admst:push into=\"$globalexpression/function\" select=\".\"/>\n"
"          <admst:value-to select=\"class\" string=\"builtin\"/>\n"
"        </admst:when>\n"
"        <!--standard functions-->\n"
"        <admst:when\n"
"          test=\"[\n"
"            name='ln' or name='log' or name='exp' or name='sqrt' or\n"
"            name='min' or name='max' or\n"
"            name='abs' or name='pow' or name='floor' or name='ceil'\n"
"          ]\">\n"
"          <admst:push into=\"$globalexpression/function\" select=\".\"/>\n"
"          <admst:value-to select=\"class\" string=\"builtin\"/>\n"
"        </admst:when>\n"
"        <!--other functions-->\n"
"        <admst:when\n"
"          test=\"[name='analysis' or name='simparam' or name='\\$limexp' or name='limexp']\">\n"
"          <admst:push into=\"$globalexpression/function\" select=\".\"/>\n"
"          <admst:value-to select=\"class\" string=\"builtin\"/>\n"
"        </admst:when>\n"
"        <!--not standard-->\n"
"        <admst:when\n"
"          test=\"[name='div' or name='\\$analysis' or name='\\$simparam' or name='\\$shrinka' or name='\\$shrinkl']\">\n"
"          <admst:push into=\"$globalexpression/function\" select=\".\"/>\n"
"          <admst:value-to select=\"class\" string=\"builtin\"/>\n"
"        </admst:when>\n"
"        <admst:otherwise>\n"
"          <admst:assert test=\"[exists(definition)]\" format=\"%(lexval/(f|':'|l|':'|c)): analog function '%(name)' is undefined\\n\"/>\n"
"        </admst:otherwise>\n"
"      </admst:choose>\n"
"      <admst:value-to select=\"subexpression/expression\" path=\"$globalexpression\"/>\n"
"      <!-- fixme: these flags should be set after all contribs are transformed to ...<+F(...); canonical form -->\n"
"      <admst:value-to test=\"[name='ddt']\" select=\"$globalcontribution/#fixmedynamic\" path=\"1\"/>\n"
"      <admst:value-to test=\"[name='white_noise']\" select=\"$globalcontribution/#fixmewhitenoise\" path=\"1\"/>\n"
"      <admst:value-to test=\"[name='flicker_noise']\" select=\"$globalcontribution/#fixmeflickernoise\" path=\"1\"/>\n"
"      <admst:value-to test=\"[name='\\$temperature']\" select=\"$globalassignment/lhs/TemperatureDependent\" string=\"yes\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='number']\">\n"
"      <admst:choose>\n"
"        <admst:when test=\"[scalingunit='1']\">\n"
"          <admst:value-to select=\"math/value\" path=\"value\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[scalingunit='E']\">\n"
"          <admst:value-to select=\"math/value\" string=\"%(value)e+18\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[scalingunit='P']\">\n"
"          <admst:value-to select=\"math/value\" string=\"%(value)e+15\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[scalingunit='T']\">\n"
"          <admst:value-to select=\"math/value\" string=\"%(value)e+12\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[scalingunit='G']\">\n"
"          <admst:value-to select=\"math/value\" string=\"%(value)e+9\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[scalingunit='M']\">\n"
"          <admst:value-to select=\"math/value\" string=\"%(value)e+6\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[scalingunit='k']\">\n"
"          <admst:value-to select=\"math/value\" string=\"%(value)e+3\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[scalingunit='h']\">\n"
"          <admst:value-to select=\"math/value\" string=\"%(value)e+2\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[scalingunit='D']\">\n"
"          <admst:value-to select=\"math/value\" string=\"%(value)e+1\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[scalingunit='d']\">\n"
"          <admst:value-to select=\"math/value\" string=\"%(value)e-1\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[scalingunit='c']\">\n"
"          <admst:value-to select=\"math/value\" string=\"%(value)e-2\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[scalingunit='m']\">\n"
"          <admst:value-to select=\"math/value\" string=\"%(value)e-3\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[scalingunit='u']\">\n"
"          <admst:value-to select=\"math/value\" string=\"%(value)e-6\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[scalingunit='n']\">\n"
"          <admst:value-to select=\"math/value\" string=\"%(value)e-9\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[scalingunit='A']\">\n"
"          <admst:value-to select=\"math/value\" string=\"%(value)e-10\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[scalingunit='p']\">\n"
"          <admst:value-to select=\"math/value\" string=\"%(value)e-12\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[scalingunit='f']\">\n"
"          <admst:value-to select=\"math/value\" string=\"%(value)e-15\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[scalingunit='a']\">\n"
"          <admst:value-to select=\"math/value\" string=\"%(value)e-18\"/>\n"
"        </admst:when>\n"
"        <admst:otherwise>\n"
"          <admst:error format=\"%(lexval/(f|':'|l|':'|c)): unit not supported: %(scalingunit)\\n\"/>\n"
"        </admst:otherwise>\n"
"      </admst:choose>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='string']\"/>\n"
"    <admst:otherwise>\n"
"      <admst:fatal format=\"%(datatypename): case not handled\\n\"/>\n"
"    </admst:otherwise>\n"
"  </admst:choose>\n"
"</admst:template>\n"
"\n"
"<admst:template match=\"init\">\n"
"  <admst:choose>\n"
"    <admst:when test=\"[datatypename='callfunction']\">\n"
"      <admst:apply-templates select=\"function/arguments\" match=\"e:init\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='whileloop']\">\n"
"      <admst:apply-templates select=\"while\" match=\"e:init\"/>\n"
"      <admst:apply-templates select=\"whileblock\" match=\"init\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='forloop']\">\n"
"      <admst:apply-templates select=\"initial|update\" match=\"init\"/>\n"
"      <admst:apply-templates select=\"condition\" match=\"e:init\"/>\n"
"      <admst:apply-templates select=\"forblock\" match=\"init\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='case']\">\n"
"      <admst:apply-templates select=\"case\" match=\"e:init\"/>\n"
"      <admst:variable name=\"globaltreenode\"/>\n"
"      <admst:for-each select=\"caseitem\">\n"
"        <admst:for-each select=\"condition\">\n"
"          <admst:variable name=\"globaltreenode\" path=\".\"/>\n"
"          <admst:apply-templates select=\".\" match=\"e:init\"/>\n"
"          <admst:variable name=\"globaltreenode\"/>\n"
"        </admst:for-each>\n"
"        <admst:apply-templates select=\"code\" match=\"init\"/>\n"
"      </admst:for-each>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='conditional']\">\n"
"      <admst:push into=\"$globalmodule/conditional\" select=\".\"/>\n"
"      <admst:apply-templates select=\"if\" match=\"e:init\"/>\n"
"      <admst:apply-templates select=\"then|else\" match=\"init\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='contribution']\">\n"
"      <admst:variable name=\"globalcontribution\" path=\".\"/>\n"
"      <admst:apply-templates select=\"rhs\" match=\"e:init\"/>\n"
"      <admst:variable name=\"globalcontribution\"/>\n"
"      <admst:push into=\"lhs/probe\" select=\"rhs/probe\" onduplicate=\"ignore\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='assignment']\">\n"
"      <admst:choose>\n"
"        <admst:when test=\"[lhs/datatypename='array']\">\n"
"          <admst:variable name=\"lhs\" path=\"lhs/variable\"/>\n"
"        </admst:when>\n"
"        <admst:otherwise>\n"
"          <admst:variable name=\"lhs\" path=\"lhs\"/>\n"
"        </admst:otherwise>\n"
"      </admst:choose>\n"
"      <admst:variable name=\"globalassignment\" path=\".\"/>\n"
"      <admst:apply-templates select=\"rhs\" match=\"e:init\"/>\n"
"      <admst:variable name=\"globalassignment\"/>\n"
"      <admst:push into=\"$lhs/probe\" select=\"rhs/probe\" onduplicate=\"ignore\"/>\n"
"      <admst:push into=\"$lhs/variable\" select=\"rhs/variable\" onduplicate=\"ignore\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='block']\">\n"
"      <admst:reverse select=\"item|variable\"/>\n"
"      <admst:apply-templates select=\"item\" match=\"init\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='nilled']\"/>\n"
"    <admst:when test=\"[datatypename='blockvariable']\"/>\n"
"    <admst:otherwise>\n"
"      <admst:fatal format=\"%(datatypename): case not handled\\n\"/>\n"
"    </admst:otherwise>\n"
"  </admst:choose>\n"
"</admst:template>\n"
"\n"
"<admst:template match=\"e:dependency\">\n"
"  <admst:choose>\n"
"    <admst:when test=\"[datatypename='expression']\">\n"
"      <admst:variable name=\"globalexpression\" path=\".\"/>\n"
"      <admst:apply-templates select=\"tree\" match=\"e:dependency\"/>\n"
"      <admst:variable name=\"globalexpression\"/>\n"
"      <admst:value-to select=\"dependency\" path=\"tree/dependency\"/>\n"
"      <admst:value-to select=\"dependency[.='constant' and $globalopdependent='yes']\" string=\"noprobe\"/>\n"
"      <admst:apply-templates select=\".\" match=\"e:partition\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='probe']\">\n"
"      <admst:value-to select=\"dependency\" string=\"linear\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='array']\">\n"
"      <admst:apply-templates select=\"variable\" match=\"e:dependency\"/>\n"
"      <admst:value-to select=\"dependency\" path=\"variable/dependency\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='variable']\">\n"
"      <admst:value-to select=\"dependency\" path=\"prototype/dependency\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='mapply_unary']\">\n"
"      <admst:apply-templates select=\"arg1\" match=\"e:dependency\"/>\n"
"      <admst:value-to select=\"dependency\" path=\"arg1/dependency\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='mapply_binary']\">\n"
"      <admst:apply-templates select=\"arg1|arg2\" match=\"e:dependency\"/>\n"
"      <!--\n"
"        +:             -:            *:            /:                                                          \n"
"          c  np l  nl    c  np l  nl   c  np l  nl   c  np nl nl                                                          \n"
"          np np l  nl    np np l  nl   np np l  nl   np np nl nl                                                          \n"
"          l  l  l  nl    l  l  l  nl   l  l  nl nl   l  l  nl nl                                                          \n"
"          nl nl nl nl    nl nl nl nl   nl nl nl nl   nl nl nl nl                                                          \n"
"      -->\n"
"      <admst:choose>\n"
"        <admst:when test=\"[arg1/dependency='nonlinear' or arg2/dependency='nonlinear']\">\n"
"          <admst:value-to select=\"dependency\" string=\"nonlinear\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[name='multtime' and (arg1|arg2)/dependency=('linear'|'linear')]\">\n"
"          <admst:value-to select=\"dependency\" string=\"nonlinear\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[name='multdiv' and arg2/dependency='linear']\">\n"
"          <admst:value-to select=\"dependency\" string=\"nonlinear\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[arg1/dependency='linear' or arg2/dependency='linear']\">\n"
"          <admst:value-to select=\"dependency\" string=\"linear\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[arg1/dependency='noprobe' or arg2/dependency='noprobe']\">\n"
"          <admst:value-to select=\"dependency\" string=\"noprobe\"/>\n"
"        </admst:when>\n"
"        <admst:otherwise>\n"
"          <admst:value-to select=\"dependency\" string=\"constant\"/>\n"
"        </admst:otherwise>\n"
"      </admst:choose>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='mapply_ternary']\">\n"
"      <admst:apply-templates select=\"arg1|arg2|arg3\" match=\"e:dependency\"/>\n"
"      <!--\n"
"          ?: - arg1=c -  - arg1!=c -                                                            \n"
"             c  np l  nl np np l  nl                                                             \n"
"             np np l  nl np np l  nl                                                             \n"
"             l  l  l  nl l  l  l  nl                                                             \n"
"             nl nl nl nl nl nl nl nl                                                             \n"
"      -->\n"
"      <admst:choose>\n"
"        <admst:when test=\"[arg2/dependency='nonlinear' or arg3/dependency='nonlinear']\">\n"
"          <admst:value-to select=\"dependency\" string=\"nonlinear\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[arg2/dependency='linear' or arg3/dependency='linear']\">\n"
"          <admst:value-to select=\"dependency\" string=\"linear\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[arg1/dependency!='constant' or arg2/dependency='noprobe' or arg3/dependency='noprobe']\">\n"
"          <admst:value-to select=\"dependency\" string=\"noprobe\"/>\n"
"        </admst:when>\n"
"        <admst:otherwise>\n"
"          <admst:value-to select=\"dependency\" string=\"constant\"/>\n"
"        </admst:otherwise>\n"
"      </admst:choose>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='function']\">\n"
"      <admst:choose>\n"
"        <admst:when test=\"[name='ddx' or name='\\$ddx' or name='\\$derivate']\">\n"
"          <admst:apply-templates select=\"arguments[1]\" match=\"e:dependency\"/>\n"
"          <admst:choose>\n"
"            <admst:when test=\"arguments[1]/dependency[.='constant' or .='noprobe']\">\n"
"              <admst:value-to select=\"dependency\" path=\"arguments[1]/dependency\"/>\n"
"            </admst:when>\n"
"            <admst:otherwise>\n"
"              <admst:value-to select=\"dependency\" string=\"nonlinear\"/>\n"
"            </admst:otherwise>\n"
"          </admst:choose>\n"
"        </admst:when>\n"
"        <admst:otherwise>\n"
"          <admst:apply-templates select=\"arguments\" match=\"e:dependency\"/>\n"
"          <admst:choose>\n"
"            <admst:when test=\"[(name='ddt' or name='\\$ddt')or(name='idt' or name='\\$idt')]\">\n"
"              <admst:value-to select=\"dependency\" string=\"nonlinear\"/>\n"
"            </admst:when>\n"
"            <admst:when test=\"arguments/dependency[.='linear' or .='nonlinear']\">\n"
"              <admst:value-to select=\"dependency\" string=\"nonlinear\"/>\n"
"            </admst:when>\n"
"            <admst:when test=\"arguments/dependency[.='noprobe']\">\n"
"              <admst:value-to select=\"dependency\" string=\"noprobe\"/>\n"
"            </admst:when>\n"
"            <admst:otherwise>\n"
"              <admst:value-to select=\"dependency\" string=\"constant\"/>\n"
"            </admst:otherwise>\n"
"          </admst:choose>\n"
"        </admst:otherwise>\n"
"      </admst:choose>\n"
"      <admst:value-to test=\"dependency[.='linear' or .='nonlinear']\" select=\"$globalexpression/hasVoltageDependentFunction\" string=\"yes\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='number']\"/>\n"
"    <admst:when test=\"[datatypename='string']\"/>\n"
"    <admst:otherwise>\n"
"      <admst:fatal format=\"%(datatypename): case not handled\\n\"/>\n"
"    </admst:otherwise>\n"
"  </admst:choose>\n"
"</admst:template>\n"
"\n"
"<admst:template match=\"dependency\">\n"
"  <admst:choose>\n"
"    <admst:when test=\"[datatypename='callfunction']\">\n"
"      <admst:apply-templates select=\"function/arguments\" match=\"e:dependency\"/>\n"
"      <admst:value-to select=\"dependency\" path=\"function/dependency\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='whileloop']\">\n"
"      <!--\n"
"        w, logic(D,while.d)            , d=wb.d                                               \n"
"              c                 !c                           \n"
"           c  wb,w,!c?(D,wb,!D) D,wb,!D                                                                                        \n"
"           !c wb                wb                                                                                             \n"
"      -->\n"
"      <admst:apply-templates select=\"while\" match=\"e:dependency\"/>\n"
"      <admst:apply-templates select=\"[$globalopdependent='yes' or while/dependency='constant']/whileblock\" match=\"dependency\"/>\n"
"      <admst:if test=\"[$globalopdependent='no']\">\n"
"        <admst:apply-templates select=\"while[dependency='constant']\" match=\"e:dependency\"/>\n"
"        <admst:if test=\"[while/dependency!='constant']\">\n"
"          <admst:variable name=\"globalopdependent\" string=\"yes\"/>\n"
"          <admst:apply-templates select=\"whileblock\" match=\"dependency\"/>\n"
"          <admst:variable name=\"globalopdependent\" string=\"no\"/>\n"
"        </admst:if>\n"
"      </admst:if>\n"
"      <!--\n"
"          wl:  w=c          w!=c\n"
"               c  np l  nl  np np l  nl                                                             \n"
"               np np l  nl  np np l  nl                                                             \n"
"               l  l  l  nl  l  l  l  nl                                                             \n"
"               nl nl nl nl  nl nl nl nl                                                             \n"
"      -->\n"
"      <admst:choose>\n"
"        <admst:when test=\"[whileblock/dependency='nonlinear']\">\n"
"          <admst:value-to select=\"dependency\" string=\"nonlinear\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[whileblock/dependency='linear']\">\n"
"          <admst:value-to select=\"dependency\" string=\"linear\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[while/dependency!='constant' or whileblock/dependency='noprobe']\">\n"
"          <admst:value-to select=\"dependency\" string=\"noprobe\"/>\n"
"        </admst:when>\n"
"        <admst:otherwise>\n"
"          <admst:value-to select=\"dependency\" string=\"constant\"/>\n"
"        </admst:otherwise>\n"
"      </admst:choose>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='forloop']\">\n"
"      <admst:apply-templates select=\"initial|update\" match=\"dependency\"/>\n"
"      <admst:apply-templates select=\"condition\" match=\"e:dependency\"/>\n"
"      <admst:apply-templates select=\"[$globalopdependent='yes' or nilled((initial|condition|update)/[dependency!='constant'])]/forblock\" match=\"dependency\"/>\n"
"      <admst:if test=\"[$globalopdependent='no']\">\n"
"        <admst:apply-templates select=\"(initial|update)/[dependency='constant']\" match=\"dependency\"/>\n"
"        <admst:apply-templates select=\"condition[dependency='constant']\" match=\"e:dependency\"/>\n"
"        <admst:if test=\"[condition/dependency!='constant' or initial/dependency!='constant' or update/dependency!='constant']\">\n"
"          <admst:variable name=\"globalopdependent\" string=\"yes\"/>\n"
"          <admst:apply-templates select=\"forblock\" match=\"dependency\"/>\n"
"          <admst:variable name=\"globalopdependent\" string=\"no\"/>\n"
"        </admst:if>\n"
"      </admst:if>\n"
"      <!--\n"
"          fl:  f=c          f!=c\n"
"               c  np l  nl  np np l  nl                                                             \n"
"               np np l  nl  np np l  nl                                                             \n"
"               l  l  l  nl  l  l  l  nl                                                             \n"
"               nl nl nl nl  nl nl nl nl                                                             \n"
"      -->\n"
"      <admst:choose>\n"
"        <admst:when test=\"[forblock/dependency='nonlinear']\">\n"
"          <admst:value-to select=\"dependency\" string=\"nonlinear\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[forblock/dependency='linear']\">\n"
"          <admst:value-to select=\"dependency\" string=\"linear\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[(condition!='constant' or initial!='constant' or update!='constant') or forblock/dependency='noprobe']\">\n"
"          <admst:value-to select=\"dependency\" string=\"noprobe\"/>\n"
"        </admst:when>\n"
"        <admst:otherwise>\n"
"          <admst:value-to select=\"dependency\" string=\"constant\"/>\n"
"        </admst:otherwise>\n"
"      </admst:choose>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='case']\">\n"
"      <admst:apply-templates select=\"case\" match=\"e:dependency\"/>\n"
"      <admst:for-each select=\"caseitem\">\n"
"        <admst:for-each select=\"condition\">\n"
"          <admst:apply-templates select=\".\" match=\"e:dependency\"/>\n"
"        </admst:for-each>\n"
"        <admst:apply-templates select=\"code\" match=\"dependency\"/>\n"
"      </admst:for-each>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='conditional']\">\n"
"      <admst:apply-templates select=\"if\" match=\"e:dependency\"/>\n"
"      <admst:choose>\n"
"        <admst:when test=\"[$globalopdependent='no' and if/dependency!='constant']\">\n"
"          <admst:variable name=\"globalopdependent\" string=\"yes\"/>\n"
"          <admst:apply-templates select=\"then|else\" match=\"dependency\"/>\n"
"          <admst:variable name=\"globalopdependent\" string=\"no\"/>\n"
"        </admst:when>\n"
"        <admst:otherwise>\n"
"          <admst:apply-templates select=\"then|else\" match=\"dependency\"/>\n"
"        </admst:otherwise>\n"
"      </admst:choose>\n"
"      <!--\n"
"          cd:  i=c          i!=c\n"
"               c  np l  nl  np np l  nl                                                             \n"
"               np np l  nl  np np l  nl                                                             \n"
"               l  l  l  nl  l  l  l  nl                                                             \n"
"               nl nl nl nl  nl nl nl nl                                                             \n"
"      -->\n"
"      <admst:choose>\n"
"        <admst:when test=\"[then/dependency='nonlinear' or else/dependency='nonlinear']\">\n"
"          <admst:value-to select=\"dependency\" string=\"nonlinear\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[then/dependency='linear' or else/dependency='linear']\">\n"
"          <admst:value-to select=\"dependency\" string=\"linear\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[if/dependency!='constant' or then/dependency='noprobe' or else/dependency='noprobe']\">\n"
"          <admst:value-to select=\"dependency\" string=\"noprobe\"/>\n"
"        </admst:when>\n"
"        <admst:otherwise>\n"
"          <admst:value-to select=\"dependency\" string=\"constant\"/>\n"
"        </admst:otherwise>\n"
"      </admst:choose>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='contribution']\">\n"
"      <admst:apply-templates select=\"rhs\" match=\"e:dependency\"/>\n"
"      <admst:value-to select=\"dependency\" string=\"nonlinear\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='assignment']\">\n"
"      <admst:choose>\n"
"        <admst:when test=\"[lhs/datatypename='array']\">\n"
"          <admst:variable name=\"lhs\" path=\"lhs/variable\"/>\n"
"        </admst:when>\n"
"        <admst:otherwise>\n"
"          <admst:variable name=\"lhs\" path=\"lhs\"/>\n"
"        </admst:otherwise>\n"
"      </admst:choose>\n"
"      <admst:choose>\n"
"        <admst:when test=\"[$globalpartitionning='initial_model']\">\n"
"          <admst:value-to select=\"$lhs/setinmodel\" string=\"yes\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[$globalpartitionning='initial_instance']\">\n"
"          <admst:value-to select=\"$lhs/setininstance\" string=\"yes\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[$globalpartitionning='initial_step']\">\n"
"          <admst:value-to select=\"$lhs/setininitial_step\" string=\"yes\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[$globalpartitionning='noise']\">\n"
"          <admst:value-to select=\"$lhs/setinnoise\" string=\"yes\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[$globalpartitionning='final_step']\">\n"
"          <admst:value-to select=\"$lhs/setinfinal\" string=\"yes\"/>\n"
"        </admst:when>\n"
"        <admst:otherwise>\n"
"          <admst:value-to select=\"$lhs/setinevaluate\" string=\"yes\"/>\n"
"        </admst:otherwise>\n"
"      </admst:choose>\n"
"      <admst:apply-templates select=\"rhs\" match=\"e:dependency\"/>\n"
"      <admst:value-to test=\"rhs/variable[TemperatureDependent='yes']\" select=\"$lhs/TemperatureDependent\" string=\"yes\"/>\n"
"      <!--\n"
"        d=rhs.d,d=(c and D)?np\n"
"        l(l,r,$globalopdependent)\n"
"        $globalopdependent='no'  $globalopdependent='yes'\n"
"        c  np l  nl               np np l  nl\n"
"        np np l  nl               np np l  nl\n"
"        l  l  l  nl               l  l  l  nl\n"
"        nl nl nl nl               nl nl nl nl\n"
"      -->\n"
"      <admst:value-to select=\"dependency\" path=\"rhs/dependency\"/>\n"
"      <admst:choose>\n"
"        <admst:when test=\"[$lhs/prototype/dependency='nonlinear' or rhs/dependency='nonlinear']\">\n"
"          <admst:value-to select=\"$lhs/(.|prototype)/dependency\" string=\"nonlinear\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[$lhs/prototype/dependency='linear' or rhs/dependency='linear']\">\n"
"          <admst:value-to select=\"$lhs/(.|prototype)/dependency\" string=\"linear\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[$globalopdependent='yes' or $lhs/prototype/dependency='noprobe' or rhs/dependency='noprobe']\">\n"
"          <admst:value-to select=\"$lhs/(.|prototype)/dependency\" string=\"noprobe\"/>\n"
"        </admst:when>\n"
"        <admst:otherwise>\n"
"          <admst:value-to select=\"$lhs/(.|prototype)/dependency\" string=\"constant\"/>\n"
"        </admst:otherwise>\n"
"      </admst:choose>      \n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='block']\">\n"
"      <admst:variable name=\"forcepartitionning\" string=\"yes\"/>\n"
"      <admst:choose>\n"
"        <admst:when test=\"[name='initial_model']\">\n"
"          <admst:variable name=\"globalpartitionning\" string=\"initial_model\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[name='initial_instance']\">\n"
"          <admst:variable name=\"globalpartitionning\" string=\"initial_instance\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[name='initial_step']\">\n"
"          <admst:variable name=\"globalpartitionning\" string=\"initial_step\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[name='noise']\">\n"
"          <admst:variable name=\"globalpartitionning\" string=\"noise\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[name='final_step']\">\n"
"          <admst:variable name=\"globalpartitionning\" string=\"final_step\"/>\n"
"        </admst:when>\n"
"        <admst:otherwise>\n"
"          <admst:variable name=\"forcepartitionning\" string=\"no\"/>\n"
"        </admst:otherwise>\n"
"      </admst:choose>\n"
"      <admst:apply-templates select=\"item\" match=\"dependency\"/>\n"
"      <admst:variable test=\"[$forcepartitionning='yes']\" name=\"globalpartitionning\"/>\n"
"      <admst:choose>\n"
"        <admst:when test=\"item[dependency='nonlinear']\">\n"
"          <admst:value-to select=\"dependency\" string=\"nonlinear\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"item[dependency='linear']\">\n"
"          <admst:value-to select=\"dependency\" string=\"linear\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"item[dependency='noprobe']\">\n"
"          <admst:value-to select=\"dependency\" string=\"noprobe\"/>\n"
"        </admst:when>\n"
"        <admst:otherwise>\n"
"          <admst:value-to select=\"dependency\" string=\"constant\"/>\n"
"        </admst:otherwise>\n"
"      </admst:choose>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='nilled']\"/>\n"
"    <admst:when test=\"[datatypename='blockvariable']\"/>\n"
"    <admst:otherwise>\n"
"      <admst:fatal format=\"%(datatypename): case not handled\\n\"/>\n"
"    </admst:otherwise>\n"
"  </admst:choose>\n"
"</admst:template>\n"
"\n"
"<admst:template match=\"e:partition\">\n"
"  <admst:fatal test=\"[datatypename!='expression']\" format=\"should be expression\\n\"/>\n"
"  <admst:choose>\n"
"    <admst:when test=\"[nilled($globalpartitionning)]\">\n"
"      <admst:value-to select=\"variable/usedinevaluate\" string=\"yes\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[$globalpartitionning='initial_model']\">\n"
"      <admst:value-to select=\"variable/usedinmodel\" string=\"yes\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[$globalpartitionning='initial_instance']\">\n"
"      <admst:value-to select=\"variable/usedininstance\" string=\"yes\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[$globalpartitionning='initial_step']\">\n"
"      <admst:value-to select=\"variable/usedininitial_step\" string=\"yes\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[$globalpartitionning='noise']\">\n"
"      <admst:value-to select=\"variable/usedinnoise\" string=\"yes\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[$globalpartitionning='final_step']\">\n"
"      <admst:value-to select=\"variable/usedinfinal\" string=\"yes\"/>\n"
"    </admst:when>\n"
"  </admst:choose>\n"
"</admst:template>\n"
"\n"
"<admst:template match=\"partition\">\n"
"  <admst:choose>\n"
"    <admst:when test=\"[datatypename='callfunction']\">\n"
"      <admst:apply-templates select=\"function/arguments\" match=\"e:partition\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='whileloop']\">\n"
"      <admst:apply-templates select=\"while\" match=\"e:partition\"/>\n"
"      <admst:apply-templates select=\"whileblock\" match=\"partition\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='forloop']\">\n"
"      <admst:apply-templates select=\"condition\" match=\"e:partition\"/>\n"
"      <admst:apply-templates select=\"initial|update|forblock\" match=\"partition\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='case']\">\n"
"      <admst:apply-templates select=\"case\" match=\"e:partition\"/>\n"
"      <admst:for-each select=\"caseitem\">\n"
"        <!-- c'est pas une expression admst:apply-templates select=\"condition\" match=\"e:partition\"/ -->\n"
"        <admst:apply-templates select=\"code\" match=\"partition\"/>\n"
"      </admst:for-each>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='conditional']\">\n"
"      <admst:apply-templates select=\"if\" match=\"e:partition\"/>\n"
"      <admst:apply-templates select=\"then|else\" match=\"partition\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='contribution']\">\n"
"      <admst:apply-templates select=\"rhs\" match=\"e:partition\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='assignment']\">\n"
"      <admst:apply-templates select=\"rhs\" match=\"e:partition\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='block']\">\n"
"      <admst:variable name=\"forcepartitionning\" string=\"yes\"/>\n"
"      <admst:choose>\n"
"        <admst:when test=\"[name='initial_model']\">\n"
"          <admst:variable name=\"globalpartitionning\" string=\"initial_model\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[name='initial_instance']\">\n"
"          <admst:variable name=\"globalpartitionning\" string=\"initial_instance\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[name='initial_step']\">\n"
"          <admst:variable name=\"globalpartitionning\" string=\"initial_step\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[name='noise']\">\n"
"          <admst:variable name=\"globalpartitionning\" string=\"noise\"/>\n"
"        </admst:when>\n"
"        <admst:when test=\"[name='final_step']\">\n"
"          <admst:variable name=\"globalpartitionning\" string=\"final_step\"/>\n"
"        </admst:when>\n"
"        <admst:otherwise>\n"
"          <admst:variable name=\"forcepartitionning\" string=\"no\"/>\n"
"        </admst:otherwise>\n"
"      </admst:choose>\n"
"      <admst:apply-templates select=\"item\" match=\"partition\"/>\n"
"      <admst:variable test=\"[$forcepartitionning='yes']\" name=\"globalpartitionning\"/>\n"
"    </admst:when>\n"
"    <admst:when test=\"[datatypename='nilled']\"/>\n"
"    <admst:when test=\"[datatypename='blockvariable']\"/>\n"
"    <admst:otherwise>\n"
"      <admst:fatal format=\"%(datatypename): case not handled\\n\"/>\n"
"    </admst:otherwise>\n"
"  </admst:choose>\n"
"</admst:template>\n"
"\n"
"<admst:template match=\"adms.implicit.xml.module\">\n"
"  <admst:variable name=\"globalmodule\" path=\".\"/>\n"
"  <admst:reverse select=\"analogfunction|analogfunction/variable|node|variable\n"
"                         |instance|instance/terminal|contribution|forloop|whileloop|case|callfunction\"/>\n"
"  <admst:value-to select=\"node[location='ground']/grounded\" string=\"yes\"/>\n"
"  <admst:for-each select=\"branch\">\n"
"    <admst:value-to select=\"discipline\" path=\"pnode/discipline\"/>\n"
"    <admst:value-to select=\"[nnode/grounded='yes']/grounded\" string=\"yes\"/>\n"
"    <!-- FIXME: check that pnode/nnode have same discipline -->\n"
"  </admst:for-each>\n"
"  <admst:for-each select=\"source|probe\">\n"
"    <admst:value-to select=\"discipline\" path=\"branch/discipline\"/>\n"
"    <admst:value-to select=\"[branch/grounded='yes']/grounded\" string=\"yes\"/>\n"
"  </admst:for-each>\n"
"  <admst:for-each select=\"instance\">\n"
"    <admst:push into=\"module/instantiator\" select=\"..\" onduplicate=\"ignore\"/>\n"
"    <admst:assert select=\"terminal\" test=\"nodefrommodule[location='external']\"\n"
"                  format=\"%(../instantiator).%(nodefrommodule/name): is not terminal\\n\"/>\n"
"    <admst:assert select=\"parameterset\" test=\"parameter[input='yes']\"\n"
"                  format=\"%(../instantiator).%(parameter/name): is not input parameter\\n\"/>\n"
"  </admst:for-each>\n"
"  <admst:apply-templates select=\"(analogfunction/tree)|(analog/code)\" match=\"init\"/>\n"
"  <admst:apply-templates select=\"(analogfunction/tree)|(analog/code)\" match=\"dependency\"/>\n"
"  <admst:apply-templates select=\"(analogfunction/tree)|(analog/code)\" match=\"partition\"/>\n"
"  <admst:for-each select=\"variable\">\n"
"    <admst:value-to select=\"[dependency!='constant']/OPdependent\" string=\"yes\"/>\n"
"    <admst:value-to select=\"output\" path=\"input\"/>\n"
"    <admst:for-each select=\"attribute\">\n"
"      <admst:value-to select=\"[name='type' and value='instance']/../parametertype\" string=\"instance\"/>\n"
"      <admst:value-to select=\"[name='ask' and value='yes']/../output\" string=\"yes\"/>\n"
"      <admst:value-to select=\"[name='ask' and value='no']/../output\" string=\"no\"/>\n"
"    </admst:for-each>\n"
"    <admst:apply-templates select=\"default\" match=\"e:dependency\"/>\n"
"    <admst:value-to\n"
"       select=\"default[exists(tree[datatypename='mapply_unary' and name='minus' and arg1/datatypename='number' and arg1/value='1.0'])]/value\"\n"
"       string=\"is_neg_one\"/>\n"
"    <admst:value-to select=\"default[exists(tree[datatypename='number' and value='0.0'])]/value\" string=\"is_zero\"/>\n"
"    <admst:value-to select=\"default[exists(tree[datatypename='number' and value='1.0'])]/value\" string=\"is_one\"/>\n"
"    <admst:value-to select=\"scope\"\n"
"      test=\"[(input='yes' and parametertype='model') or (input='no' and (setinmodel='yes' or usedinmodel='yes')\n"
"        and (setininstance='yes' or setininitial_step='yes' or setinevaluate='yes' or setinnoise='yes' or setinfinal='yes'\n"
"        or usedininstance='yes' or usedininitial_step='yes' or usedinevaluate='yes' or usedinnoise='yes' or usedinfinal='yes' or output='yes'))]\"\n"
"      string=\"global_model\"/>\n"
"    <admst:value-to select=\"scope\"\n"
"      test=\"[(input='yes' and parametertype='instance') or\n"
"      (input='no' and setinmodel='no' and usedinmodel='no' and\n"
"        (((setininstance='yes' or usedininstance='yes') and (setininitial_step='yes' or setinevaluate='yes' or setinnoise='yes' or setinfinal='yes'\n"
"        or usedininitial_step='yes' or usedinevaluate='yes' or usedinnoise='yes' or usedinfinal='yes' or output='yes'))\n"
"        or ((setininitial_step='yes' or usedininitial_step='yes') and (setinevaluate='yes' or setinnoise='yes' or setinfinal='yes'\n"
"        or usedinevaluate='yes' or usedinnoise='yes' or usedinfinal='yes' or output='yes'))\n"
"        or ((setinevaluate='yes' or usedinevaluate='yes') and (setinnoise='yes' or setinfinal='yes'\n"
"          or usedinnoise='yes' or usedinfinal='yes' or output='yes'))\n"
"        or ((setinnoise='yes' or usedinnoise='yes') and (setinfinal='yes' or usedinfinal='yes' or output='yes'))\n"
"        or ((setinfinal='yes' or usedinfinal='yes') and output='yes')\n"
"        or (setinmodel='no' and setininstance='no' and setinevaluate='no' and setinnoise='no' and setinfinal='no' and\n"
"            usedinmodel='no' and usedininstance='no' and usedinevaluate='no' and usedinnoise='no' and usedinfinal='no' and output='yes')\n"
"      ))]\"\n"
"      string=\"global_instance\"/>\n"
"    <admst:value-to select=\"isstate\"\n"
"      test=\"[input='no' and scope='global_instance' and setininitial_step='yes' and (setinevaluate='yes' or usedinevaluate='yes')]\"\n"
"      string=\"yes\"/>\n"
"  </admst:for-each>\n"
"  <admst:template match=\"modify\">\n"
"    <admst:choose>\n"
"      <admst:when test=\"[datatypename='block']\">\n"
"        <admst:apply-templates select=\"reverse(item)\" match=\"modify\"/>\n"
"        <admst:value-to test=\"item[#modifys=1]\" select=\"#modifys\" path=\"1\"/>\n"
"        <admst:value-to test=\"item[#modifyd=1]\" select=\"#modifyd\" path=\"1\"/>\n"
"        <admst:value-to test=\"item[#modifyn=1]\" select=\"#modifyn\" path=\"1\"/>\n"
"        <admst:value-to test=\"item[#modifyc=1]\" select=\"#modifyc\" path=\"1\"/>\n"
"      </admst:when>\n"
"      <admst:when test=\"[datatypename='conditional']\">\n"
"        <admst:apply-templates select=\"else|then\" match=\"modify\"/>\n"
"        <admst:value-to test=\"[then/#modifys=1 or else/#modifys=1]\" select=\"#modifys|if/#modifys|if/variable/#modifys\" path=\"1\"/>\n"
"        <admst:value-to test=\"[then/#modifyd=1 or else/#modifyd=1]\" select=\"#modifyd|if/#modifyd|if/variable/#modifyd\" path=\"1\"/>\n"
"        <admst:value-to test=\"[then/#modifyn=1 or else/#modifyn=1]\" select=\"#modifyn|if/#modifyn|if/variable/#modifyn\" path=\"1\"/>\n"
"        <admst:value-to test=\"[then/#modifyc=1 or else/#modifyc=1]\" select=\"#modifyc|if/#modifyc|if/variable/#modifyc\" path=\"1\"/>\n"
"      </admst:when>\n"
"      <admst:when test=\"[datatypename='whileloop']\">\n"
"        <admst:apply-templates select=\"whileblock\" match=\"modify\"/>\n"
"        <admst:value-to test=\"[whileblock/#modifys=1]\" select=\"#modifys|while/#modifys|while/variable/#modifys\" path=\"1\"/>\n"
"        <admst:value-to test=\"[whileblock/#modifyd=1]\" select=\"#modifyd|while/#modifyd|while/variable/#modifyd\" path=\"1\"/>\n"
"        <admst:value-to test=\"[whileblock/#modifyn=1]\" select=\"#modifyn|while/#modifyn|while/variable/#modifyn\" path=\"1\"/>\n"
"        <admst:value-to test=\"[whileblock/#modifyc=1]\" select=\"#modifyc|while/#modifyc|while/variable/#modifyc\" path=\"1\"/>\n"
"        <admst:apply-templates select=\"whileblock\" match=\"modify\"/>\n"
"      </admst:when>\n"
"      <admst:when test=\"[datatypename='forloop']\">\n"
"        <admst:choose>\n"
"          <admst:when test=\"[update/lhs/datatypename='array']\">\n"
"            <admst:variable name=\"lhs\" path=\"update/lhs/variable\"/>\n"
"          </admst:when>\n"
"          <admst:otherwise>\n"
"            <admst:variable name=\"lhs\" path=\"update/lhs\"/>\n"
"          </admst:otherwise>\n"
"        </admst:choose>\n"
"        <admst:apply-templates select=\"forblock\" match=\"modify\"/>\n"
"        <admst:value-to test=\"[forblock/#modifys=1]\" select=\"#modifys|(condition|update)/#modifys|(condition|update/rhs)/($lhs|variable)/#modifys\" path=\"1\"/>\n"
"        <admst:value-to test=\"[forblock/#modifyd=1]\" select=\"#modifyd|(condition|update)/#modifyd|(condition|update/rhs)/($lhs|variable)/#modifyd\" path=\"1\"/>\n"
"        <admst:value-to test=\"[forblock/#modifyn=1]\" select=\"#modifyn|(condition|update)/#modifyn|(condition|update/rhs)/($lhs|variable)/#modifyn\" path=\"1\"/>\n"
"        <admst:value-to test=\"[forblock/#modifyc=1]\" select=\"#modifyc|(condition|update)/#modifyc|(condition|update/rhs)/($lhs|variable)/#modifyc\" path=\"1\"/>\n"
"        <admst:apply-templates select=\"forblock\" match=\"modify\"/>\n"
"      </admst:when>\n"
"      <admst:when test=\"[datatypename='case']\">\n"
"        <admst:apply-templates select=\"caseitem/code\" match=\"modify\"/>\n"
"        <admst:for-each select=\"caseitem\">\n"
"          <admst:value-to test=\"[code/#modifys=1 and defaultcase='no']\" select=\"#modifys|condition/#modifys|condition/@variable/#modifys\" path=\"1\"/>\n"
"          <admst:value-to test=\"[code/#modifyd=1 and defaultcase='no']\" select=\"#modifyd|condition/#modifyd|condition/@variable/#modifyd\" path=\"1\"/>\n"
"          <admst:value-to test=\"[code/#modifyn=1 and defaultcase='no']\" select=\"#modifyn|condition/#modifyn|condition/@variable/#modifyn\" path=\"1\"/>\n"
"          <admst:value-to test=\"[code/#modifyc=1 and defaultcase='no']\" select=\"#modifyc|condition/#modifyc|condition/@variable/#modifyc\" path=\"1\"/>\n"
"        </admst:for-each>\n"
"        <admst:value-to test=\"caseitem[#modifys=1]\" select=\"#modifys|case/@variable/#modifys\" path=\"1\"/>\n"
"        <admst:value-to test=\"caseitem[#modifyd=1]\" select=\"#modifyd|case/@variable/#modifyd\" path=\"1\"/>\n"
"        <admst:value-to test=\"caseitem[#modifyn=1]\" select=\"#modifyn|case/@variable/#modifyn\" path=\"1\"/>\n"
"        <admst:value-to test=\"caseitem[#modifyc=1]\" select=\"#modifyc|case/@variable/#modifyc\" path=\"1\"/>\n"
"      </admst:when>\n"
"      <admst:when test=\"[datatypename='assignment']\">\n"
"        <admst:choose>\n"
"          <admst:when test=\"[lhs/datatypename='array']\">\n"
"            <admst:variable name=\"lhs\" path=\"lhs/variable\"/>\n"
"          </admst:when>\n"
"          <admst:otherwise>\n"
"            <admst:variable name=\"lhs\" path=\"lhs\"/>\n"
"          </admst:otherwise>\n"
"        </admst:choose>\n"
"        <admst:value-to test=\"$lhs[exists(prototype/instance[#modifys=1])]\" select=\"#modifys|rhs/#modifys|rhs/variable/#modifys\" path=\"1\"/>\n"
"        <admst:value-to test=\"$lhs[exists(prototype/instance[#modifyd=1])]\" select=\"#modifyd|rhs/#modifys|rhs/variable/#modifyd\" path=\"1\"/>\n"
"        <admst:value-to test=\"$lhs[exists(prototype/instance[#modifyn=1])]\" select=\"#modifyn|rhs/#modifys|rhs/variable/#modifyn\" path=\"1\"/>\n"
"        <admst:value-to test=\"$lhs[exists(prototype/instance[#modifyc=1])]\" select=\"#modifyc|rhs/#modifys|rhs/variable/#modifyc\" path=\"1\"/>\n"
"        <admst:value-to test=\"$lhs/ddxprobe\" select=\"#ddxprobe\" string=\"yes\"/>\n"
"        <admst:push into=\"rhs/variable/ddxprobe\" select=\"$lhs/ddxprobe\" onduplicate=\"ignore\"/>\n"
"      </admst:when>\n"
"      <admst:when test=\"[datatypename='contribution']\">\n"
"        <admst:choose>\n"
"          <admst:when test=\"[#fixmedynamic=1]\">\n"
"            <admst:value-to select=\"#modifyd|(lhs|rhs|rhs/variable)/#modifyd\" path=\"1\"/>\n"
"          </admst:when>\n"
"          <admst:when test=\"[#fixmeflickernoise=1]\">\n"
"            <admst:value-to select=\"flickernoise|lhs/flickernoise\" string=\"yes\"/>\n"
"            <admst:value-to select=\"#modifyn|(lhs|rhs|rhs/variable)/#modifyn\" path=\"1\"/>\n"
"          </admst:when>\n"
"          <admst:when test=\"[#fixmewhitenoise=1]\">\n"
"            <admst:value-to select=\"whitenoise|lhs/whitenoise\" string=\"yes\"/>\n"
"            <admst:value-to select=\"#modifyn|(lhs|rhs|rhs/variable)/#modifyn\" path=\"1\"/>\n"
"          </admst:when>\n"
"          <admst:otherwise>\n"
"            <admst:value-to select=\"#modifys|(lhs|rhs|rhs/variable)/#modifys\" path=\"1\"/>\n"
"          </admst:otherwise>\n"
"        </admst:choose>\n"
"      </admst:when>\n"
"      <admst:when test=\"[datatypename='blockvariable']\">\n"
"      </admst:when>\n"
"      <admst:when test=\"[datatypename='nilled']\"/>\n"
"      <admst:when test=\"[datatypename='callfunction']\">\n"
"        <admst:value-to select=\"#modifyc|function/arguments/variable/#modifyc\" path=\"1\"/>\n"
"      </admst:when>\n"
"      <admst:otherwise><admst:fatal format=\"%(datatypename): case not handled\\n\"/></admst:otherwise>\n"
"    </admst:choose>\n"
"  </admst:template>\n"
"  <admst:apply-templates select=\"analog/code\" match=\"modify\"/>\n"
"  <admst:push into=\"@analogitems\" select=\"assignment|assignment/rhs|contribution|contribution/rhs|block|forloop|whileloop|case|callfunction|conditional|conditional/if\"/>\n"
"  <admst:value-to select=\"@analogitems[#modifys=1 or #modifyn=1 or #modifyc=1]/static\" string=\"yes\"/>\n"
"  <admst:value-to select=\"@analogitems[#modifys!=1 and #modifyn!=1 and #modifyc!=1]/dynamic\" string=\"yes\"/>\n"
"\n"
"  <admst:value-to select=\"(.|blockvariable)/variable[exists(instance[#modifys=1])]/#modifys\" path=\"1\"/>\n"
"  <admst:value-to select=\"(.|blockvariable)/variable[exists(instance[#modifyd=1])]/#modifyd\" path=\"1\"/>\n"
"  <admst:value-to select=\"(.|blockvariable)/variable[exists(instance[#modifyn=1])]/#modifyn\" path=\"1\"/>\n"
"  <admst:value-to select=\"(.|blockvariable)/variable[exists(instance[#modifyc=1])]/#modifyc\" path=\"1\"/>\n"
"\n"
"  <admst:value-to select=\"(.|blockvariable)/variable[exists(instance[#modifys=1 or #modifyd=1 or #modifyn=1])]/insource\" string=\"yes\"/>\n"
"  <admst:value-to select=\"(.|blockvariable)/variable[exists(instance[#modifys=1 or #modifyn=1 or #modifyc=1])]/static\" string=\"yes\"/>\n"
"  <admst:value-to select=\"(.|blockvariable)/variable[exists(instance[#modifyd=1])]/dynamic\" string=\"yes\"/>\n"
"  <admst:value-to select=\"source[#modifys=1 or #modifyn=1]/static\" string=\"yes\"/>\n"
"  <admst:value-to select=\"source[#modifyd=1]/dynamic\" string=\"yes\"/>\n"
"\n"
"  <!-- jacobian -->\n"
"  <admst:for-each select=\"contribution\">\n"
"    <admst:variable name=\"mycontribution\" path=\".\"/>\n"
"    <admst:variable name=\"mysource\" path=\"lhs\"/>\n"
"    <admst:push into=\"$mysource/attribute\" select=\"attribute\"/>\n"
"    <!-- case I() <+ .V(). -->\n"
"    <admst:for-each select=\"rhs/probe[(nature=discipline/potential)and($mysource/nature=$mysource/discipline/flow)]\">\n"
"      <admst:new datatype=\"jacobian\" inputs=\"module,$mysource/branch/pnode,branch/pnode\">\n"
"        <admst:push into=\"/@jacobian\" select=\".\" onduplicate=\"ignore\"/>\n"
"      </admst:new>\n"
"      <admst:new test=\"branch/nnode[grounded='no']\" datatype=\"jacobian\" inputs=\"module,$mysource/branch/pnode,branch/nnode\">\n"
"        <admst:push into=\"/@jacobian\" select=\".\" onduplicate=\"ignore\"/>\n"
"      </admst:new>\n"
"      <admst:new test=\"$mysource/branch/nnode[grounded='no']\" datatype=\"jacobian\" inputs=\"module,$mysource/branch/nnode,branch/pnode\">\n"
"        <admst:push into=\"/@jacobian\" select=\".\" onduplicate=\"ignore\"/>\n"
"        <admst:new test=\"../branch/nnode[grounded='no']\" datatype=\"jacobian\" inputs=\"module,$mysource/branch/nnode,../branch/nnode\">\n"
"          <admst:push into=\"/@jacobian\" select=\".\" onduplicate=\"ignore\"/>\n"
"        </admst:new>\n"
"      </admst:new>\n"
"      <admst:for-each select=\"/reverse(@jacobian)\">\n"
"        <admst:choose>\n"
"          <admst:when test=\"module/jacobian[row=../../row and column=../../column]\">\n"
"            <admst:variable name=\"jacobian\" path=\"module/jacobian[row=../../row and column=../../column]\"/>\n"
"          </admst:when>\n"
"          <admst:otherwise>\n"
"            <admst:variable name=\"jacobian\" path=\".\"/>\n"
"            <admst:value-to select=\"[row=column]/diagonal\" string=\"yes\"/>\n"
"            <admst:push into=\"module/jacobian\" select=\".\"/>\n"
"          </admst:otherwise>\n"
"        </admst:choose>\n"
"        <admst:value-to test=\"$mycontribution[dynamic='yes']\" select=\"$jacobian/dynamic\" string=\"yes\"/>\n"
"        <admst:value-to test=\"$mycontribution[dynamic='no']\" select=\"$jacobian/static\" string=\"yes\"/>\n"
"      </admst:for-each>\n"
"      <admst:value-to select=\"/@jacobian\"/>\n"
"    </admst:for-each>\n"
"  </admst:for-each>\n"
"  <admst:reverse select=\"jacobian\"/>\n"
"</admst:template>\n"
"\n"
"<admst:template match=\"adms.implicit.xml.nature\">\n"
"  <admst:reverse select=\"/argv|/discipline|/nature\"/>\n"
"  <admst:for-each select=\"/nature\">\n"
"    <admst:value-to select=\"ddt_nature\" path=\"/nature[name='%(../../ddt_name)']\"/>\n"
"    <admst:value-to select=\"idt_nature\" path=\"/nature[name='%(../../idt_name)']\"/>\n"
"  </admst:for-each>\n"
"</admst:template>\n"
"\n"
"<admst:template match=\"adms.implicit.xml\">\n"
"  <admst:apply-templates select=\".\" match=\"adms.implicit.xml.nature\"/>\n"
"  <admst:apply-templates select=\"/module\" match=\"adms.implicit.xml.module\"/>\n"
"</admst:template>\n"
"\n"
"<admst:apply-templates select=\".\" match=\"adms.implicit.xml\"/>\n"
"\n"
"<!--admst:sendmail>\n"
"  <admst:subject>automatic mailing from %(/simulator/fullname)</admst:subject>\n"
"  <admst:arguments recipient=\"%(/simulator/fullname)\"/>\n"
"  <admst:to recipient=\"r29173@freescale.com\"/>\n"
"  <admst:message>\n"
"  </admst:message>\n"
"</admst:sendmail-->\n"
"\n"
"\n"
"</admst>\n"
;
