/* File automatically created by ./mkctext.pl*/

const char * dummy_xml = ""
"<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n"
"<!DOCTYPE admst SYSTEM \"admst.dtd\">\n"
"<admst version=\"2.3.0\" xmlns:admst=\"http://mot-adms.sourceforge.net/xml-files/admst\">\n"
"<admst:template match=\"print_expression\">\n"
"  <admst:choose>\n"
"    <admst:when test=\"[datatypename='number']\">%(value)%(scalingunit)</admst:when>\n"
"    <admst:otherwise>-%(datatypename)-not-done-yet--</admst:otherwise>\n"
"  </admst:choose>\n"
"</admst:template>\n"
"<admst:for-each select=\"/module\">\n"
"<admst:variable name=\"mname\" select=\"%(name)\"/>\n"
"<admst:message format=\"build file %(name).net\\n\"/>\n"
"<admst:open file=\"%(name).net\">\n"
"<admst:text format=\"*** Interface: %(/simulator/package_string)\\n\"/>\n"
"<admst:text format=\"*** created by: %(/simulator/fullname) - %(/simulator/currentdate)\\n\"/>\n"
"<admst:text format=\"\\n\"/>\n"
"  <admst:text format=\"* Simple test circuit - automatically created %(/simulator/currentdate) \\n\"/>\n"
"  <admst:text format=\"\\n\"/>\n"
"  <admst:text format=\".options scale=1 gmin=1e-12 reltol=1.0e-8 vabstol=1.0e-08\\n\"/>\n"
"  <admst:text format=\"\\n\"/>\n"
"  <admst:text format=\"model my$mname $mname\\n\"/>\n"
"  <admst:for-each select=\"variable[scope='global_model']\">\n"
"    <admst:if test=\"[input='yes']\">\n"
"      <admst:text format=\"+ %(name) = %(print_expression(default/tree))\\n\"/>\n"
"    </admst:if>\n"
"  </admst:for-each>\n"
"  <admst:text format=\"\\n\"/>\n"
"  <admst:text format=\"$mname \"/>\n"
"  <admst:text select=\"node[location='external']\" format=\"N_$(mname)_%(name)_int \"/>\n"
"  <admst:text format=\"my$mname  \\n\"/>\n"
"  <admst:for-each select=\"variable[scope='global_instance']\">\n"
"    <admst:if test=\"[input='yes']\">\n"
"      <admst:choose>\n"
"        <admst:when test=\"attribute[name='spice:isflag' and value='yes']\">\n"
"        </admst:when>\n"
"        <admst:otherwise>\n"
"          <admst:choose>\n"
"            <admst:when test=\"attribute[name='spice:name']\">\n"
"              <admst:for-each select=\"attribute[name='spice:name']\">\n"
"                <admst:text format=\"+ %(value) = %(print_expression(default/tree))\\n\"/>\n"
"              </admst:for-each>\n"
"            </admst:when>\n"
"            <admst:otherwise>\n"
"              <admst:text format=\"+ %(name) = %(print_expression(default/tree))\\n\"/>\n"
"            </admst:otherwise>\n"
"          </admst:choose>\n"
"        </admst:otherwise>\n"
"      </admst:choose>\n"
"    </admst:if>\n"
"  </admst:for-each>\n"
"  <admst:text format=\"\\n\"/>\n"
"  <admst:for-each select=\"node[location='external']\">\n"
"    <admst:text format=\"* inout node \\n\"/>\n"
"    <admst:text format=\"v_$(mname)_%(name)_vdd N_$(mname)_%(name)_vdd 0 vsource dc=1.0\\n\"/>\n"
"    <admst:text format=\"r_$(mname)_%(name)1  N_$(mname)_%(name)_int 0 resistor r=1.0\\n\"/>\n"
"    <admst:text format=\"r_$(mname)_%(name)2  N_$(mname)_%(name)_int N_$(mname)_%(name)_vdd resistor r=1.0\\n\"/>\n"
"  </admst:for-each>\n"
"  <admst:text format=\"\\n\"/>\n"
"  <admst:text format=\"opPoint dc oppoint=screen print=yes\\n\"/>\n"
"  <admst:text format=\"* infoall info what=all save=all\\n\"/>\n"
"</admst:open>\n"
"</admst:for-each>\n"
"\n"
"</admst>\n"
;
