/* File automatically created by ./mkctext.pl*/

const char * dummy_va = ""
"// DUMMY EXAMPLE\n"
"`include\"discipline.h\"\n"
"module dummy(p,q);\n"
" inout  p,q;\n"
" // external nodes\n"
" (* desc=\"+ node\"*) electrical p;\n"
" (* desc=\"- node\"*) electrical q;\n"
"// Branch definitions\n"
" branch (q ,q)  pq;   //           branch from p to q\n"
"// Parameter definitions\n"
" (* desc=\"resistance value\" unit=\"Ohm\" *)\n"
" parameter real R =  1.0;\n"
"// Variable definitions\n"
" (* desc=\"clamped conductance value\" unit=\"1/Ohm\" *)\n"
" real g;\n"
" analog\n"
" begin\n"
"   begin\n"
"    g = (R>0.1) ? 1.0/R : 10.0;\n"
"    I(p,q) <+ g*V(p,q);\n"
"   end\n"
" end\n"
"endmodule\n"
;
