#line 2 "preprocessorLex.c"

#line 4 "preprocessorLex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer preprocessor_create_buffer
#define yy_delete_buffer preprocessor_delete_buffer
#define yy_flex_debug preprocessor_flex_debug
#define yy_init_buffer preprocessor_init_buffer
#define yy_flush_buffer preprocessor_flush_buffer
#define yy_load_buffer_state preprocessor_load_buffer_state
#define yy_switch_to_buffer preprocessor_switch_to_buffer
#define yyin preprocessorin
#define yyleng preprocessorleng
#define yylex preprocessorlex
#define yylineno preprocessorlineno
#define yyout preprocessorout
#define yyrestart preprocessorrestart
#define yytext preprocessortext
#define yywrap preprocessorwrap
#define yyalloc preprocessoralloc
#define yyrealloc preprocessorrealloc
#define yyfree preprocessorfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE preprocessorrestart(preprocessorin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int preprocessorleng;

extern FILE *preprocessorin, *preprocessorout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up preprocessortext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up preprocessortext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via preprocessorrestart()), so that the user can continue scanning by
	 * just pointing preprocessorin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when preprocessortext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int preprocessorleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow preprocessorwrap()'s to do buffer switches
 * instead of setting up a fresh preprocessorin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void preprocessorrestart (FILE *input_file  );
void preprocessor_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE preprocessor_create_buffer (FILE *file,int size  );
void preprocessor_delete_buffer (YY_BUFFER_STATE b  );
void preprocessor_flush_buffer (YY_BUFFER_STATE b  );
void preprocessorpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void preprocessorpop_buffer_state (void );

static void preprocessorensure_buffer_stack (void );
static void preprocessor_load_buffer_state (void );
static void preprocessor_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER preprocessor_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE preprocessor_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE preprocessor_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE preprocessor_scan_bytes (yyconst char *bytes,int len  );

void *preprocessoralloc (yy_size_t  );
void *preprocessorrealloc (void *,yy_size_t  );
void preprocessorfree (void *  );

#define yy_new_buffer preprocessor_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        preprocessorensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            preprocessor_create_buffer(preprocessorin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        preprocessorensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            preprocessor_create_buffer(preprocessorin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *preprocessorin = (FILE *) 0, *preprocessorout = (FILE *) 0;

typedef int yy_state_type;

extern int preprocessorlineno;

int preprocessorlineno = 1;

extern char *preprocessortext;
#define yytext_ptr preprocessortext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up preprocessortext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	preprocessorleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 77
#define YY_END_OF_BUFFER 78
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[329] =
    {   0,
       10,   10,   78,   76,   77,    6,   76,   77,    5,   77,
       76,   77,   76,   77,   76,   77,   73,   76,   77,   74,
       76,   77,   75,   76,   77,   76,   77,   72,   76,   77,
       76,   77,   76,   77,    6,   76,   77,   76,   77,   76,
       77,   62,   77,   59,   62,   77,   77,   62,   77,   62,
       77,   68,   77,   63,   68,   77,   67,   77,   68,   77,
       68,   77,   68,   77,   57,   77,   55,   57,   77,   56,
       77,   57,   77,   57,   77,   54,   57,   77,   57,   77,
       77,   69,   77,   77,   23,   77,   21,   23,   77,   22,
       77,   23,   77,   23,   77,   23,   77,16402,16403,   10,

       77,   11,   77,   10,   77,   27,   77,   24,   27,   77,
       25,   77,   27,   77,   27,   77,   30,   77,   40,   77,
       37,   40,   77,   39,   77,   40,   77,   40,   77,   51,
       77,   48,   51,   77,16425,   53,   77,   51,   77,   51,
       77,   45,   51,   77,   46,   51,   77,   47,   51,   77,
       51,   77,   44,   51,   77,   51,   77,   51,   77,   36,
       77,   35,   36,   77,   34,   36,   77,   33,   36,   77,
       32,   77,   32,   77,   31,   32,   77,    6,    4,    1,
       72,    8,   72,    2,   71,16454,    6,   71,16454,   71,
    16454,   71,16454,   71,16454,   59,   60,   63,   67,   64,

       66,   55,   56,   54,   54,   58,   69,   21,   22,16402,
    16403, 8211, 8210,   20,16402,16403,   10,   11,   24,   25,
       26,   30,   28,   37,   39,   38,   48,16425, 8233,   53,
       44,   49,   44,   52,   43,16426,   35,   31,   31,    8,
     8262,   71,16454,   71,16454,   71,16454,   71,16454,   71,
    16454,   71,16454,   71,16454,   61,   64,   29,   49, 8234,
       43,16426,    7,   71,16454,   71,16454,   71,16454,   71,
    16454,   71,16454,   71,16454,   71,16454,   65,   50,   71,
    16454,   15,   71,16454,   71,16454,   71,16454,   71,16454,
       71,16454,   71,16454,   15,   71,16454,   16,   71,16454,

       13,   71,16454,   71,16454,   71,16454,   12,   71,16454,
       16,   13,   12,    3,    9,   71,16454,   14,   71,16454,
       71,16454,    9,   14,   17,   71,16454,   17
    } ;

static yyconst flex_int16_t yy_accept[295] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    4,
        6,    9,   11,   13,   15,   17,   20,   23,   26,   28,
       31,   33,   35,   38,   40,   42,   44,   47,   48,   50,
       52,   54,   57,   59,   61,   63,   65,   67,   70,   72,
       74,   76,   79,   81,   82,   84,   85,   87,   90,   92,
       94,   96,  100,  102,  104,  106,  108,  111,  113,  115,
      117,  119,  121,  124,  126,  128,  130,  132,  136,  138,

      140,  142,  145,  148,  151,  153,  156,  158,  160,  162,
      165,  168,  171,  173,  175,  178,  179,  180,  180,  181,
      182,  182,  183,  184,  185,  185,  185,  187,  188,  188,
      188,  190,  192,  194,  196,  197,  197,  198,  198,  199,
      200,  200,  201,  202,  202,  203,  204,  205,  206,  207,
      207,  207,  208,  208,  209,  210,  212,  213,  214,  214,
      215,  217,  218,  219,  220,  221,  222,  222,  222,  223,
      224,  225,  226,  227,  227,  229,  230,  230,  231,  232,
      232,  233,  234,  235,  235,  235,  237,  238,  239,  240,
      240,  240,  241,  241,  242,  244,  244,  244,  244,  244,

      244,  246,  248,  250,  252,  254,  256,  257,  257,  257,
      258,  259,  259,  259,  259,  260,  260,  261,  263,  263,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      266,  268,  270,  272,  274,  276,  278,  278,  279,  279,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  282,  285,  287,  289,  291,  293,  295,  295,
      295,  295,  295,  295,  296,  296,  296,  296,  296,  296,
      296,  298,  301,  304,  306,  308,  311,  311,  312,  313,
      313,  313,  314,  315,  315,  318,  321,  323,  324,  325,
      325,  328,  329,  329

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    7,    8,    1,    1,    1,    9,
       10,   11,    1,   12,    1,    1,   13,   14,   15,   15,
       15,   15,   15,   15,   15,   15,   15,    1,    1,   16,
        1,   17,    1,    1,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
        1,   19,    1,    1,   18,   20,   18,   18,   21,   22,

       23,   24,   18,   18,   25,   18,   18,   26,   18,   27,
       18,   18,   18,   18,   28,   18,   29,   18,   18,   18,
       18,   18,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[30] =
    {   0,
        1,    2,    3,    4,    5,    1,    1,    6,    5,    1,
        1,    1,    1,    7,    7,    1,    8,    9,    1,    1,
        9,    9,    9,    9,    9,    9,    9,    9,    9
    } ;

static yyconst flex_int16_t yy_base[335] =
    {   0,
        0,   28,   47,   62,   77,   95,  114,    0,   28,   33,
      143,    0,   35,   37,  171,  189,  748,  747,  207,  225,
      244,    0,  272,  283,  295,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  755,  758,
       40,  758,  751,  747,    0,  758,  758,  758,   33,    0,
       51,  744,   54,   55,  317,  758,   56,  758,  745,    0,
      758,   64,  758,  747,   59,   72,  758,   81,  758,  746,
        0,    0,   81,   84,  758,   88,  758,   99,  758,  745,
        0,  345,    0,  758,  744,  758,  100,  758,  743,   90,
      101,  758,  105,  758,  742,  109,  758,  175,  758,  741,

        0,  758,  758,  758,   60,    0,  178,  735,  758,  181,
      758,  758,  758,    0,    0,  182,  758,  736,  758,    0,
      730,    0,    0,  758,  737,  731,   38,  183,  173,  199,
      208,  192,  197,  209,  195,  732,  758,  720,  220,  758,
      725,    0,  758,  732,  232,  758,    0,    0,  758,  731,
      202,  758,  235,  238,  758,  353,  274,  758,  730,  758,
        0,    0,  758,  276,  758,  758,  729,  323,  361,  758,
      278,  758,  758,  728,  287,  758,  727,  758,    0,  718,
        0,    0,  758,  725,  719,  323,  329,    0,    0,  715,
      222,    0,  332,  758,  702,  701,  215,  311,  696,  370,

      306,  345,  321,  347,  330,  337,  758,  711,  366,    0,
      377,  379,  710,  375,    0,  385,  758,  386,  709,  758,
      695,  690,  695,  370,  695,  629,  394,  643,    0,  378,
      619,  379,  618,  383,  384,  601,  612,  758,  599,  758,
      597,  398,  576,  577,  562,  561,  561,  554,  540,  553,
      410,  390,  534,  395,  397,  519,   66,  399,  528,  403,
      510,  413,  493,  758,  493,  401,  385,  369,  369,  425,
      355,  344,  338,  408,  411,  329,  322,  758,  758,  312,
      272,  758,  758,  284,  200,  193,  184,  758,  758,  176,
      166,  758,  758,  434,  443,  452,  461,  470,  479,  488,

      497,  506,  100,  509,  513,  522,  531,   68,  534,  543,
       53,  551,  560,  569,   42,  572,  576,   25,  579,  588,
      597,  602,  611,  620,  629,  638,  643,  652,  661,  670,
      679,  688,  697,  706
    } ;

static yyconst flex_int16_t yy_def[335] =
    {   0,
      293,    1,  294,  294,  295,  295,  293,    7,  296,  296,
      293,   11,  297,  297,  298,  298,  299,  299,  300,  300,
      293,   21,  301,  301,  293,   25,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  293,  293,
      293,  293,  293,  302,  303,  293,  293,  293,  293,  304,
      293,  305,  293,  293,  305,  293,  293,  293,  306,  307,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      308,  309,  293,  310,  293,  310,  293,  293,  293,  293,
      311,  312,  313,  293,  313,  293,  293,  293,  293,  293,
      314,  293,  293,  293,  293,  293,  293,  293,  293,  293,

      315,  293,  293,  293,  293,  316,  293,  317,  293,  293,
      293,  293,  293,  318,  319,  293,  293,  302,  293,  304,
      320,  321,  304,  293,  293,  305,  322,  293,  293,  293,
      322,  131,  131,  131,  293,  306,  293,  307,  293,  293,
      323,  324,  293,  293,  293,  293,  309,  309,  293,  293,
      310,  293,  310,  293,  293,  312,  293,  293,  293,  293,
      156,  313,  293,  293,  293,  293,  293,  314,  314,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  316,  325,
      326,  316,  293,  293,  317,  327,  293,  319,  319,  320,
      328,  321,  293,  293,  131,  293,  293,  293,  293,  293,

      131,  131,  131,  131,  131,  131,  293,  323,  329,  324,
      314,  314,  325,  330,  326,  293,  293,  327,  331,  293,
      293,  293,  293,  293,  293,  293,  293,  332,  200,  131,
      131,  131,  131,  131,  131,  131,  333,  293,  334,  293,
      331,  328,  293,  293,  293,  293,  293,  293,  293,  332,
      293,  131,  131,  131,  131,  131,  131,  131,  333,  329,
      334,  330,  293,  293,  293,  293,  293,  293,  293,  293,
      131,  131,  131,  131,  131,  131,  293,  293,  293,  293,
      293,  293,  293,  293,  131,  131,  131,  293,  293,  293,
      131,  293,    0,  293,  293,  293,  293,  293,  293,  293,

      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293
    } ;

static yyconst flex_int16_t yy_nxt[788] =
    {   0,
       40,   41,   42,   43,   41,   44,   40,   45,   46,   47,
       40,   48,   49,   40,   40,   40,   40,   50,   51,   52,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   53,
       75,   76,   53,  188,   54,   75,   76,   84,   85,   84,
       85,  116,  193,  121,  116,  122,  194,   55,   57,   58,
      179,   57,   59,  124,  125,  128,  130,  135,  128,  130,
      135,  156,   60,   57,   58,  139,   57,   59,  139,  141,
      180,  142,  181,  129,  143,  144,  147,   60,   62,   63,
       64,   62,  145,  149,  150,  145,  152,  153,  195,   65,
      152,  153,  166,  167,  275,   66,   62,   63,   64,   62,

      154,  164,  169,  154,  164,  169,  171,   65,  120,  171,
      170,  173,  174,   66,   67,   68,   69,   70,   68,   67,
       67,   71,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   72,   73,   67,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   77,   78,   79,   80,   78,   77,   77,
       81,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       82,   77,   77,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   87,   88,   89,   87,  175,  176,  177,  175,
      183,  184,  187,  116,  128,  187,  116,  128,  195,   90,
       87,   88,   89,   87,  196,  197,  135,  198,  292,  135,

      130,  199,  129,  130,  152,  153,  291,   90,   93,   94,
       95,   93,  193,  200,  195,  195,  194,  202,  203,  195,
      204,  139,  195,  205,  139,   96,   93,   94,   95,   93,
      201,  195,  191,  145,  220,  206,  145,  152,  153,  154,
      222,  223,  154,   96,   97,   98,   99,  100,   98,   97,
       97,  101,  102,  103,   97,  104,  105,   97,   97,   97,
       97,  106,  107,  108,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  110,   58,  157,  110,  164,  157,  171,
      164,  111,  171,  112,  110,   58,  283,  110,  175,  176,
      177,  175,  111,  290,  112,  113,  113,   58,  113,  113,

      113,  113,  114,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  115,  113,  113,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  126,  211,  212,  216,  195,  230,
      187,  217,  293,  187,  224,  289,  193,  225,  131,  132,
      194,  133,  232,  195,  288,  134,  157,  158,  159,  157,
      235,  195,  195,  160,  157,  158,  159,  157,  236,  195,
      195,  160,  169,  211,  212,  169,  195,  195,  233,  195,
      170,  227,  231,  234,  227,  228,  209,  285,  238,  211,
      212,  211,  212,  229,  229,  214,  293,  240,  293,  216,
      216,  246,  282,  217,  217,  227,  247,  281,  227,  228,

      195,  195,  252,  254,  256,  195,  195,  280,  242,  257,
      220,  270,  195,  260,  270,  238,  271,  195,  272,  195,
      273,  195,  276,  262,  279,  240,  270,  283,  284,  270,
      195,  286,  287,  195,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   92,   92,
       92,   92,   92,   92,   92,   92,   92,  109,  109,  109,

      109,  109,  109,  109,  109,  109,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  123,  278,  123,  127,  277,
      262,  127,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  138,  138,  138,  138,  138,  138,  138,  260,  138,
      148,  274,  148,  151,  151,  151,  151,  151,  151,  151,
      151,  151,  161,  161,  161,  161,  195,  161,  251,  161,
      162,  162,  269,  162,  162,  162,  162,  162,  162,  168,
      168,  168,  168,  168,  168,  168,  168,  168,  182,  268,
      182,  186,  267,  266,  186,  189,  265,  189,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  192,  192,  264,

      263,  192,  192,  192,  192,  192,  195,  242,  195,  262,
      195,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      210,  210,  260,  258,  210,  210,  210,  210,  210,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  215,  215,
      255,  253,  215,  215,  215,  215,  215,  218,  251,  218,
      249,  218,  219,  219,  219,  219,  219,  219,  219,  219,
      219,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  259,  259,  259,

      259,  259,  259,  259,  259,  259,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  248,  245,  244,  243,  242,
      214,  209,  226,  221,  195,  191,  293,  183,  214,  176,
      173,  166,  158,  149,  143,  209,  207,  137,  293,  124,
      191,  119,  185,  178,  172,  165,  163,  155,  146,  140,
      137,  126,  119,  117,  293,   91,   91,   39,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293
    } ;

static yyconst flex_int16_t yy_chk[788] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        9,    9,    2,  318,    2,   10,   10,   13,   13,   14,
       14,   41,  127,   49,   41,   49,  127,    2,    3,    3,
      315,    3,    3,   51,   51,   53,   54,   57,   53,   54,
       57,  311,    3,    4,    4,   62,    4,    4,   62,   65,
      105,   65,  105,   53,   66,   66,  308,    4,    5,    5,
        5,    5,   68,   73,   73,   68,   74,   74,  257,    5,
       76,   76,   90,   90,  257,    5,    6,    6,    6,    6,

       78,   87,   91,   78,   87,   91,   93,    6,  303,   93,
       91,   96,   96,    6,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   15,   15,   15,   15,   98,   98,   98,   98,
      107,  107,  110,  116,  128,  110,  116,  128,  291,   15,
       16,   16,   16,   16,  129,  129,  135,  129,  290,  135,

      130,  129,  128,  130,  151,  151,  287,   16,   19,   19,
       19,   19,  131,  130,  132,  286,  131,  132,  132,  133,
      133,  139,  285,  133,  139,   19,   20,   20,   20,   20,
      131,  134,  191,  145,  191,  134,  145,  153,  153,  154,
      197,  197,  154,   20,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   23,   23,  157,   23,  164,  157,  171,
      164,   23,  171,   23,   24,   24,  284,   24,  175,  175,
      175,  175,   24,  281,   24,   25,   25,   25,   25,   25,

       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   55,  168,  168,  186,  201,  201,
      187,  186,  168,  187,  198,  280,  193,  198,   55,   55,
      193,   55,  203,  203,  277,   55,   82,   82,   82,   82,
      205,  276,  205,   82,  156,  156,  156,  156,  206,  206,
      273,  156,  169,  169,  169,  169,  272,  202,  204,  204,
      169,  200,  202,  204,  200,  200,  209,  271,  209,  211,
      211,  212,  212,  200,  200,  214,  211,  214,  212,  216,
      218,  224,  269,  216,  218,  227,  224,  268,  227,  227,

      230,  232,  230,  232,  234,  234,  235,  267,  242,  235,
      242,  251,  252,  260,  251,  260,  252,  254,  254,  255,
      255,  258,  258,  262,  266,  262,  270,  270,  270,  270,
      274,  274,  275,  275,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  301,  301,  301,

      301,  301,  301,  301,  301,  301,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  304,  265,  304,  305,  263,
      261,  305,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  307,  307,  307,  307,  307,  307,  307,  259,  307,
      309,  256,  309,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  312,  312,  312,  312,  253,  312,  250,  312,
      313,  313,  249,  313,  313,  313,  313,  313,  313,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  316,  248,
      316,  317,  247,  246,  317,  319,  245,  319,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  321,  321,  244,

      243,  321,  321,  321,  321,  321,  322,  241,  322,  239,
      322,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      324,  324,  237,  236,  324,  324,  324,  324,  324,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  326,  326,
      233,  231,  326,  326,  326,  326,  326,  327,  228,  327,
      226,  327,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  333,  333,  333,

      333,  333,  333,  333,  333,  333,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  225,  223,  222,  221,  219,
      213,  208,  199,  196,  195,  190,  185,  184,  180,  177,
      174,  167,  159,  150,  144,  141,  138,  136,  126,  125,
      121,  118,  108,  100,   95,   89,   85,   80,   70,   64,
       59,   52,   44,   43,   39,   18,   17,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293
    } ;

extern int preprocessor_flex_debug;
int preprocessor_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up preprocessortext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *preprocessortext;
#line 1 "preprocessorLex.l"
#line 2 "preprocessorLex.l"

#include "adms.h"
#include "admsPreprocessor.h"
#include "preprocessorYacc.h"

#ifndef INITIAL
#  define INITIAL 0
#endif

#include "constants.vams.c"
#include "disciplines.vams.c"

#define yyflex_unput \
{\
  int i;\
  char *yycopy=strdup(preprocessortext);\
  for ( i = preprocessorleng - 1; i >= 0; --i )\
    unput(yycopy[i]);\
  free(yycopy);\
}

#define DONT_SKIPP (pproot()->skipp_text->data==INT2ADMS(0))

void adms_preprocessor_setfile_input (FILE *ifile)
{
  preprocessorin = ifile;
}

FILE *adms_preprocessor_getfile_input (void)
{
  return preprocessorin;
}

void adms_preprocessor_setfile_output (FILE *ifile)
{
  preprocessorout = ifile;
}

FILE *adms_preprocessor_getfile_output (void)
{
  return preprocessorout;
}

#define tkreturn(token) {pproot()->cr_scanner->cur_char_position+=preprocessorleng; return token;}

static char* adms_preprocessor_lex_remove_leading_quote (char* name)
{
  char* unquoted_name;
  char* start;
  char* finish;
  start = name+1;
  finish = name + strlen(name);
  unquoted_name = adms_knclone (start, finish - start );
  return (unquoted_name);
}

static char* adms_preprocessor_lex_get_path (char* macro, const char begin, const char end)
{
  char* path;
  char* start=macro;
  char* finish;
  while( *start && (*start != begin) )
    start++;
  finish=++start;
  while( *finish && (*finish != end) )
    finish++;
  path=adms_knclone (start, finish - start );
  return path;
}

void preprocessorerror (const char *message)
{
  p_preprocessor cr_preprocessor=pproot()->cr_scanner;
  adms_message_fatal (("[%s:%i]:%s: %s\n",
    cr_preprocessor->filename,
    adms_preprocessor_get_line_position(cr_preprocessor,cr_preprocessor->cur_char_position-preprocessorleng),
    message,
    cr_preprocessor->cur_message?cr_preprocessor->cur_message:"(unknown)"
  ))
}
static void adms_file_fprintf ( char *filename, const char *filedata)
{
  FILE *ofh = fopen (filename,"w");
  if (fprintf (ofh, filedata)==EOF)
    adms_message_fatal(("%s: cannot write file\n", filename))
  fclose (ofh);
}
static FILE* adms_file_open_read_with_path (const char* myfilename, p_slist mypath)
{
  p_slist l; for(l=mypath;l;l=l->next)
  {
    FILE* myfh=NULL;
    char* mypathname=strdup((char*)(l->data));
    adms_k2strconcat(&mypathname,ADMS_PATH_SEPARATOR);
    adms_k2strconcat(&mypathname,myfilename);
    if((myfh=fopen(mypathname,"r")))
      return myfh;
  }
  return NULL;
}
static void adms_preprocessor_lex_include_file (char* fileName)
{
  FILE*myfh;
  p_preprocessor scanner;
  char*message=NULL;
  adms_k2strconcat(&message,pproot()->cr_scanner->filename);
  adms_k2strconcat(&message,":");
  adms_strconcat(&message,adms_integertostring(adms_preprocessor_get_line_position (pproot()->cr_scanner, 0)));
  if(pproot()->cr_filename)
    free(pproot()->cr_filename);
  pproot()->cr_filename=strdup(fileName);
  if(!(myfh=adms_file_open_read_with_path(fileName,(p_slist)(pproot()->includePath))))
  {
    if(!strcmp(fileName,"discipline.h")||!strcmp(fileName,"disciplines.h")||!strcmp(fileName,"discipline.vams")||!strcmp(fileName,"disciplines.vams"))
    {
      adms_message_warning(("[%s]: standard vams file created (not found in -I path) ... '%s'\n",message,fileName))
      adms_file_fprintf(fileName,disciplines_vams);
      myfh=adms_file_open_read(fileName);
    }
    else if(!strcmp(fileName,"constant.h")||!strcmp(fileName,"constants.h")||!strcmp(fileName,"constant.vams")||!strcmp(fileName,"constants.vams"))
    {
      adms_message_warning(("[%s]: standard vams file created (not found in -I path) ... '%s'\n",message,fileName))
      adms_file_fprintf(fileName,constants_vams);
      myfh=adms_file_open_read(fileName);
    }
    else
      adms_message_fatal(("[%s]: failed to open file ... '%s'\n",message,fileName))
  }
  scanner=(p_preprocessor)malloc(sizeof(t_preprocessor));
  adms_message_verbose(("include file '%s'\n",fileName))
  scanner->buffer=NULL;
  scanner->fid=NULL;
  scanner->cur_continuator_position=NULL;
  pproot()->cr_scanner->buffer = (p_adms)YY_CURRENT_BUFFER;
  adms_slist_push(&pproot()->Scanner,(void*)pproot()->cr_scanner );
  preprocessorin = myfh;
  scanner->fid = preprocessorin;
  scanner->cur_line_position = 1;
  scanner->cur_char_position = 1;
  scanner->filename=strdup(pproot()->cr_filename);
  scanner->buffer = (void*) preprocessor_create_buffer(preprocessorin,YY_BUF_SIZE );
  pproot()->cr_scanner = scanner;
  preprocessor_switch_to_buffer((YY_BUFFER_STATE)scanner->buffer );
  preprocessorlval.mystr = NULL;
  adms_k2strconcat(&preprocessorlval.mystr,"# 1 \"");
  adms_k2strconcat(&preprocessorlval.mystr,pproot()->cr_scanner->filename);
  adms_k2strconcat(&preprocessorlval.mystr,"\"\n");
  BEGIN( INITIAL );
  free(message);
}

static char *adms_preprocessor_lex_skipp_text ()
{
  char *c;
  int nbline=0;
  c = preprocessortext;
  while (*c)
  {
    if(*c=='\n')
    {
      pproot()->cr_scanner->cur_char_position = 1;
      pproot()->cr_scanner->cur_line_position++;
      nbline++;
    }
    else
      pproot()->cr_scanner->cur_char_position++;
    c++;
  }
  if(nbline)
  {
    char*str=(char*)malloc(sizeof(char)*(nbline+1));
    memset(str,'\n',nbline);
    str[nbline] = '\0';
    return str;
  }
  else
    return strdup("");
}



















#line 995 "preprocessorLex.c"

#define INITIAL 0
#define PRAGMA_PATH 1
#define PRAGMA_COMMENT 2
#define PRAGMA_NAME 3
#define PRAGMA_ERROR 4
#define PRAGMA_DEFINE_START 5
#define PRAGMA_DEFINE_IGNORE 6
#define PRAGMA_DEFINE_NOARG 7
#define PRAGMA_DEFINE_WITHARG 8
#define PRAGMA_DEFINE_TEXT_START 9
#define PRAGMA_DEFINE_TEXT 10
#define PRAGMA_DEFINE_WITHARG_COMMA 11
#define PRAGMA_DEFINE_WITHARG_ARGS 12
#define PRAGMA_SUBSTITUTOR_START 13
#define PRAGMA_SUBSTITUTOR_ARG 14
#define PRAGMA_SUBSTITUTOR_PAIR 15
#define PRAGMA_SUBSTITUTOR_ARGITEM 16
#define PRAGMA_SUBSTITUTOR_ARGCOMMA 17
#define PRAGMA_SUBSTITUTOR_ARGEND 18

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int preprocessorlex_destroy (void );

int preprocessorget_debug (void );

void preprocessorset_debug (int debug_flag  );

YY_EXTRA_TYPE preprocessorget_extra (void );

void preprocessorset_extra (YY_EXTRA_TYPE user_defined  );

FILE *preprocessorget_in (void );

void preprocessorset_in  (FILE * in_str  );

FILE *preprocessorget_out (void );

void preprocessorset_out  (FILE * out_str  );

int preprocessorget_leng (void );

char *preprocessorget_text (void );

int preprocessorget_lineno (void );

void preprocessorset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int preprocessorwrap (void );
#else
extern int preprocessorwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( preprocessortext, preprocessorleng, 1, preprocessorout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( preprocessorin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( preprocessorin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, preprocessorin))==0 && ferror(preprocessorin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(preprocessorin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int preprocessorlex (void);

#define YY_DECL int preprocessorlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after preprocessortext and preprocessorleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( preprocessorleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(preprocessortext[preprocessorleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 218 "preprocessorLex.l"


#line 1201 "preprocessorLex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)preprocessoralloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in preprocessorlex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! preprocessorin )
			preprocessorin = stdin;

		if ( ! preprocessorout )
			preprocessorout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			preprocessorensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				preprocessor_create_buffer(preprocessorin,YY_BUF_SIZE );
		}

		preprocessor_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of preprocessortext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 294 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 758 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 220 "preprocessorLex.l"
{
  preprocessorlval.mystr = strdup( preprocessortext );
  tkreturn(TK_STRING)
}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 225 "preprocessorLex.l"
{
  p_continuator continuator;

  continuator=(p_continuator)malloc(sizeof(t_continuator));
  continuator->char_position = preprocessorleng-1;
  continuator->line_position = pproot()->cr_scanner->cur_line_position;

  pproot()->cr_scanner->cur_line_position += 1;
  pproot()->cr_scanner->cur_char_position = 1;
  adms_slist_push(&(pproot()->cr_scanner->cur_continuator_position),(p_adms)continuator);

  tkreturn(TK_NOPRAGMA_CONTINUATOR)
}
	YY_BREAK
/* ignored sequences */
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 241 "preprocessorLex.l"
{
}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 244 "preprocessorLex.l"
{
  preprocessorlval.mystr=strdup(preprocessortext);
  return(TK_EOL);
}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 248 "preprocessorLex.l"
{
  preprocessorlval.mystr=strdup(preprocessortext);
  return(TK_EOL);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 253 "preprocessorLex.l"
{
  pproot()->cr_scanner->cur_char_position+=preprocessorleng; 
  preprocessorlval.mystr=strdup(preprocessortext);
  return(TK_SPACE );
}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 259 "preprocessorLex.l"
{
  preprocessorlval.mystr=adms_preprocessor_lex_skipp_text (); return(TK_COMMENT);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 263 "preprocessorLex.l"
{
  preprocessorlval.mystr=adms_preprocessor_lex_skipp_text (); return(TK_COMMENT);
}
	YY_BREAK
/* pragma */
case 9:
YY_RULE_SETUP
#line 269 "preprocessorLex.l"
{
  pproot()->cr_scanner->cur_char_position+=preprocessorleng; 
  if ( DONT_SKIPP )
    {
      BEGIN( PRAGMA_DEFINE_START );
      tkreturn(TK_DEFINE)
    }
  else
      BEGIN( PRAGMA_DEFINE_IGNORE );
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 279 "preprocessorLex.l"
{
  pproot()->cr_scanner->cur_char_position+=preprocessorleng; 
  BEGIN( INITIAL );
}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 283 "preprocessorLex.l"
{
  pproot()->cr_scanner->cur_message=strdup("- `define: unexpected end-of-line");
  yyflex_unput
  BEGIN( INITIAL );
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 289 "preprocessorLex.l"
{
  if ( DONT_SKIPP )
    {
      BEGIN( PRAGMA_NAME );
      tkreturn(TK_UNDEF)
    }
  else
      BEGIN( PRAGMA_DEFINE_IGNORE );
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 298 "preprocessorLex.l"
{
  preprocessorlval.mystr=strdup("");;
  BEGIN( PRAGMA_NAME );
  tkreturn(TK_IFDEF)
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 303 "preprocessorLex.l"
{
  preprocessorlval.mystr=strdup("");;
  BEGIN( PRAGMA_NAME );
  tkreturn(TK_IFNDEF)
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 308 "preprocessorLex.l"
{
  char* string=NULL;
  adms_k2strconcat(&string,"# ");
  adms_strconcat(&string,adms_integertostring(pproot()->cr_scanner->cur_line_position+1));
  adms_k2strconcat(&string," \"");
  adms_k2strconcat(&string,pproot()->cr_scanner->filename);
  adms_k2strconcat(&string,"\"");
  preprocessorlval.mystr=string;
  BEGIN( PRAGMA_COMMENT );
  tkreturn(TK_ELSE)
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 319 "preprocessorLex.l"
{
  char* string=NULL;
  adms_k2strconcat(&string,"# ");
  adms_strconcat(&string,adms_integertostring(pproot()->cr_scanner->cur_line_position+1));
  adms_k2strconcat(&string," \"");
  adms_k2strconcat(&string,pproot()->cr_scanner->filename);
  adms_k2strconcat(&string,"\"");
  preprocessorlval.mystr=string;
  BEGIN( PRAGMA_COMMENT );
  tkreturn(TK_ENDIF)
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 330 "preprocessorLex.l"
{
  if(DONT_SKIPP)
    BEGIN(PRAGMA_PATH);
  else
    BEGIN(PRAGMA_DEFINE_IGNORE);
}
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 337 "preprocessorLex.l"
{
  BEGIN( PRAGMA_DEFINE_NOARG );
  preprocessorlval.mystr=strdup(preprocessortext );
  tkreturn(TK_PRAGMA_NAME)
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 342 "preprocessorLex.l"
{
  BEGIN( PRAGMA_DEFINE_NOARG );
  preprocessorlval.mystr=strdup(preprocessortext );
  tkreturn(TK_PRAGMA_NAME)
}
	YY_BREAK
case 20:
*yy_cp = (yy_hold_char); /* undo effects of setting up preprocessortext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up preprocessortext again */
YY_RULE_SETUP
#line 347 "preprocessorLex.l"
{
  BEGIN( PRAGMA_DEFINE_WITHARG );
  preprocessorlval.mystr=strdup(preprocessortext );
  tkreturn(TK_PRAGMA_NAME)
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 352 "preprocessorLex.l"
{
  pproot()->cr_scanner->cur_char_position+=preprocessorleng; 
}
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 355 "preprocessorLex.l"
{
  pproot()->cr_scanner->cur_message=strdup("- pragma name: unexpected end-of-line");
  yyflex_unput
  BEGIN( PRAGMA_ERROR );
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 360 "preprocessorLex.l"
{
  char* string=NULL;
  adms_k2strconcat(&string,"at character ");
  adms_k2strconcat(&string,preprocessortext);
  adms_k2strconcat(&string," - identifier was expected");
  pproot()->cr_scanner->cur_message=string;
  yyflex_unput
  BEGIN( PRAGMA_ERROR );
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 370 "preprocessorLex.l"
{
  pproot()->cr_scanner->cur_char_position+=preprocessorleng; 
}
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 373 "preprocessorLex.l"
{
  pproot()->cr_scanner->cur_message=strdup("- `define: unexpected end-of-line)");
  yyflex_unput
  BEGIN( INITIAL );
  tkreturn(TK_DEFINE_END)
}
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 379 "preprocessorLex.l"
{
  p_continuator continuator;

  continuator=(p_continuator)malloc(sizeof(t_continuator));
  continuator->char_position = preprocessorleng-1;
  continuator->line_position = pproot()->cr_scanner->cur_line_position;

  pproot()->cr_scanner->cur_line_position += 1;
  pproot()->cr_scanner->cur_char_position = 1;
  adms_slist_push(&(pproot()->cr_scanner->cur_continuator_position),(p_adms)continuator);

  tkreturn(TK_CONTINUATOR)
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 392 "preprocessorLex.l"
{
  char* string=NULL;
  adms_k2strconcat(&string,"at character ");
  adms_k2strconcat(&string,preprocessortext);
  adms_k2strconcat(&string," - whitespace was expected");
  pproot()->cr_scanner->cur_message=string;
  yyflex_unput
  BEGIN( PRAGMA_DEFINE_TEXT_START );
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 402 "preprocessorLex.l"
{
  pproot()->cr_scanner->cur_char_position+=preprocessorleng; 
  BEGIN( PRAGMA_DEFINE_TEXT_START );
  tkreturn(TK_ARG_NULL)
}
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 407 "preprocessorLex.l"
{
  char* string=NULL;
  adms_k2strconcat(&string,"at character ");
  adms_k2strconcat(&string,preprocessortext);
  adms_k2strconcat(&string," - `define has no closing paren");
  pproot()->cr_scanner->cur_message=string;
  yyflex_unput
  BEGIN( PRAGMA_ERROR );
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 416 "preprocessorLex.l"
{
  pproot()->cr_scanner->cur_char_position+=preprocessorleng; 
  BEGIN( PRAGMA_DEFINE_WITHARG_ARGS );
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 421 "preprocessorLex.l"
{
  BEGIN( PRAGMA_DEFINE_WITHARG_COMMA );
  preprocessorlval.mystr=strdup(preprocessortext );
  tkreturn(TK_ARG)
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 426 "preprocessorLex.l"
{
  char* string=NULL;
  adms_k2strconcat(&string,"at character ");
  adms_k2strconcat(&string,preprocessortext);
  adms_k2strconcat(&string," - `define has unexpected syntax");
  pproot()->cr_scanner->cur_message=string;
  yyflex_unput
  BEGIN( PRAGMA_ERROR );
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 436 "preprocessorLex.l"
{
  pproot()->cr_scanner->cur_char_position+=preprocessorleng; 
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 439 "preprocessorLex.l"
{
  pproot()->cr_scanner->cur_char_position+=preprocessorleng; 
  BEGIN( PRAGMA_DEFINE_TEXT_START );
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 443 "preprocessorLex.l"
{
  pproot()->cr_scanner->cur_char_position+=preprocessorleng; 
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 446 "preprocessorLex.l"
{
  yyflex_unput
  BEGIN( PRAGMA_DEFINE_WITHARG_ARGS );
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 451 "preprocessorLex.l"
{
  pproot()->cr_scanner->cur_char_position+=preprocessorleng; 
  BEGIN( PRAGMA_DEFINE_TEXT );
}
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 455 "preprocessorLex.l"
{
  p_continuator continuator;

  continuator=(p_continuator)malloc(sizeof(t_continuator));
  continuator->char_position = preprocessorleng-1;
  continuator->line_position = pproot()->cr_scanner->cur_line_position;

  pproot()->cr_scanner->cur_line_position += 1;
  pproot()->cr_scanner->cur_char_position = 1;
  adms_slist_push(&(pproot()->cr_scanner->cur_continuator_position),(p_adms)continuator);

  tkreturn(TK_CONTINUATOR)
}
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 468 "preprocessorLex.l"
{
  yyflex_unput
  BEGIN( INITIAL );
  tkreturn(TK_DEFINE_END)
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 473 "preprocessorLex.l"
{
  yyflex_unput
  BEGIN( PRAGMA_DEFINE_TEXT );
}
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 478 "preprocessorLex.l"
{
  pproot()->cr_scanner->cur_char_position+=preprocessorleng; 
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 482 "preprocessorLex.l"
{

  preprocessorlval.mystr=strdup(adms_preprocessor_lex_remove_leading_quote( preprocessortext ));
  if(DONT_SKIPP)
  {
    p_preprocessor_pragma_define Define;
    if ((Define = adms_preprocessor_pragma_define_exists (preprocessorlval.mystr)))
    {
      if(adms_preprocessor_pragma_define_has_noarg(Define))
        tkreturn(TK_SUBSTITUTOR_NOARG)
      else if(adms_preprocessor_pragma_define_has_nullarg(Define))
        tkreturn(TK_SUBSTITUTOR_NULLARG)
      else
        tkreturn(TK_SUBSTITUTOR_WITHARG)
    }
    else
    {
       preprocessorlval.mystr = strdup(preprocessortext);
       pproot()->cr_scanner->cur_message=strdup(preprocessortext);
       tkreturn(TK_ERROR_PRAGMA_NOT_FOUND)
    }
  }
  else
    tkreturn(TK_IDENT)
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 508 "preprocessorLex.l"
{

  preprocessorlval.mystr=strdup(adms_preprocessor_lex_remove_leading_quote( preprocessortext ));
  if(DONT_SKIPP)
  {
    p_preprocessor_pragma_define Define;
    if((Define=adms_preprocessor_pragma_define_exists (preprocessorlval.mystr)))
    {
      if(adms_preprocessor_pragma_define_has_noarg(Define))
        tkreturn(TK_SUBSTITUTOR_NOARG)
      else if(adms_preprocessor_pragma_define_has_nullarg(Define))
        tkreturn(TK_SUBSTITUTOR_NULLARG_ALONE)
      else
        tkreturn(TK_SUBSTITUTOR_WITHARG_ALONE)
    }
    else
    {
       preprocessorlval.mystr=strdup(preprocessortext);
       pproot()->cr_scanner->cur_message=strdup(preprocessortext);
       tkreturn(TK_ERROR_PRAGMA_NOT_FOUND)
    }
  }
  else
    tkreturn(TK_IDENT)
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 534 "preprocessorLex.l"
{

  preprocessorlval.mystr = strdup(preprocessortext);
  tkreturn(TK_IDENT)
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 540 "preprocessorLex.l"
{
  preprocessorlval.mystr = strdup(preprocessortext);
  tkreturn('(')
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 545 "preprocessorLex.l"
{
  preprocessorlval.mystr = strdup(preprocessortext);
  tkreturn(')')
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 550 "preprocessorLex.l"
{
  preprocessorlval.mystr = strdup(preprocessortext);
  tkreturn(',')
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 555 "preprocessorLex.l"
{
  pproot()->cr_scanner->cur_char_position+=preprocessorleng; 
  preprocessorlval.mystr=strdup(preprocessortext);
  return(TK_SPACE );
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 561 "preprocessorLex.l"
{
  preprocessorlval.mystr=adms_preprocessor_lex_skipp_text (); return(TK_COMMENT);
}
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 565 "preprocessorLex.l"
{
  preprocessorlval.mystr=adms_preprocessor_lex_skipp_text (); return(TK_COMMENT);
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 569 "preprocessorLex.l"
{
  preprocessorlval.mystr = strdup(preprocessortext);
  tkreturn(TK_NOT_IDENT)
}
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 574 "preprocessorLex.l"
{
  p_continuator continuator;

  continuator=(p_continuator)malloc(sizeof(t_continuator));
  continuator->char_position = preprocessorleng-1;
  continuator->line_position = pproot()->cr_scanner->cur_line_position;

  pproot()->cr_scanner->cur_line_position += 1;
  pproot()->cr_scanner->cur_char_position = 1;
  adms_slist_push(&(pproot()->cr_scanner->cur_continuator_position),(p_adms)continuator);

  tkreturn(TK_CONTINUATOR)
}
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 587 "preprocessorLex.l"
{
  yyflex_unput
  BEGIN( INITIAL );
  tkreturn(TK_DEFINE_END)
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 593 "preprocessorLex.l"
{
  BEGIN( PRAGMA_COMMENT );
  preprocessorlval.mystr=strdup(preprocessortext );
  tkreturn(TK_PRAGMA_NAME)
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 598 "preprocessorLex.l"
{
  pproot()->cr_scanner->cur_char_position+=preprocessorleng; 
}
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 601 "preprocessorLex.l"
{
  pproot()->cr_scanner->cur_message=strdup("- unexpected end-of-line");
  yyflex_unput
  BEGIN( PRAGMA_ERROR );
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 606 "preprocessorLex.l"
{
  char* string=NULL;
  adms_k2strconcat(&string,"at character ");
  adms_k2strconcat(&string,preprocessortext);
  adms_k2strconcat(&string," - pragma name was expected");
  pproot()->cr_scanner->cur_message=string;
  yyflex_unput
  BEGIN( PRAGMA_ERROR );
}
	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 615 "preprocessorLex.l"
{
  p_continuator continuator;

  continuator=(p_continuator)malloc(sizeof(t_continuator));
  continuator->char_position = preprocessorleng-1;
  continuator->line_position = pproot()->cr_scanner->cur_line_position;

  pproot()->cr_scanner->cur_line_position += 1;
  pproot()->cr_scanner->cur_char_position = 1;
  adms_slist_push(&(pproot()->cr_scanner->cur_continuator_position),(p_adms)continuator);

  tkreturn(TK_CONTINUATOR)
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 629 "preprocessorLex.l"
{
  pproot()->cr_scanner->cur_char_position+=preprocessorleng; 
}
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 632 "preprocessorLex.l"
{
  char* fileName;
  BEGIN( INITIAL );
  fileName = adms_preprocessor_lex_get_path(preprocessortext,'"','"');
  adms_preprocessor_lex_include_file(fileName);
  tkreturn(TK_INCLUDE)
}
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 639 "preprocessorLex.l"
{
  char* fileName;
  BEGIN( INITIAL );
  fileName = adms_preprocessor_lex_get_path(preprocessortext,'<','>');
  adms_message_info(("%s: implicit path handled as explicit path!",fileName))
  adms_preprocessor_lex_include_file(fileName);
  tkreturn(TK_INCLUDE)
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 647 "preprocessorLex.l"
{
  char* string=NULL;
  adms_k2strconcat(&string,"at character ");
  adms_k2strconcat(&string,preprocessortext);
  adms_k2strconcat(&string," - bad path");
  pproot()->cr_scanner->cur_message=string;
  yyflex_unput
  BEGIN( PRAGMA_ERROR );
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 657 "preprocessorLex.l"
{
  pproot()->cr_scanner->cur_char_position+=preprocessorleng; 
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 660 "preprocessorLex.l"
{
  preprocessorlval.mystr=adms_preprocessor_lex_skipp_text (); return(TK_COMMENT);
}
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 663 "preprocessorLex.l"
{
  preprocessorlval.mystr=adms_preprocessor_lex_skipp_text (); return(TK_COMMENT);
}
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 666 "preprocessorLex.l"
{
  p_continuator continuator;

  continuator=(p_continuator)malloc(sizeof(t_continuator));
  continuator->char_position = preprocessorleng-1;
  continuator->line_position = pproot()->cr_scanner->cur_line_position;

  pproot()->cr_scanner->cur_line_position += 1;
  pproot()->cr_scanner->cur_char_position = 1;
  adms_slist_push(&(pproot()->cr_scanner->cur_continuator_position),(p_adms)continuator);

  tkreturn(TK_CONTINUATOR)

}
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 680 "preprocessorLex.l"
{
  yyflex_unput
  BEGIN( INITIAL );
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 684 "preprocessorLex.l"
{
  char* string=NULL;
  adms_k2strconcat(&string,"at character ");
  adms_k2strconcat(&string,preprocessortext);
  adms_k2strconcat(&string," - unknown error");
  pproot()->cr_scanner->cur_message=string;
  yyflex_unput
  BEGIN( PRAGMA_ERROR );
}
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 694 "preprocessorLex.l"
{
  char* string=NULL;
  adms_k2strconcat(&string,"at character ");
  adms_k2strconcat(&string,preprocessortext);
  adms_k2strconcat(&string," - unknown error");
  pproot()->cr_scanner->cur_message=string;
  tkreturn(TK_ERROR_PRAGMA_DEFINITION)
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 703 "preprocessorLex.l"
{

  p_preprocessor_pragma_define Define;
  preprocessorlval.mystr = 
    strdup(adms_preprocessor_lex_remove_leading_quote( preprocessortext));
  if(DONT_SKIPP)
  {
    if ((Define = adms_preprocessor_pragma_define_exists (preprocessorlval.mystr)))
    {
      if(adms_preprocessor_pragma_define_has_noarg(Define))
        tkreturn(TK_SUBSTITUTOR_NOARG)
      else if(adms_preprocessor_pragma_define_has_nullarg(Define))
        tkreturn(TK_SUBSTITUTOR_NULLARG)
      else
        tkreturn(TK_SUBSTITUTOR_WITHARG)
    }
    else
    {
      preprocessorlval.mystr = strdup(preprocessortext);
      pproot()->cr_scanner->cur_message=strdup(preprocessortext);
      tkreturn(TK_ERROR_PRAGMA_NOT_FOUND)
    }
  }
  else
    tkreturn(TK_IDENT)

}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 731 "preprocessorLex.l"
{

  preprocessorlval.mystr = 
    strdup(adms_preprocessor_lex_remove_leading_quote( preprocessortext ));
  {
    p_preprocessor_pragma_define Define;
    if(DONT_SKIPP)
    {
      if((Define=adms_preprocessor_pragma_define_exists (preprocessorlval.mystr)))
      {
        if(adms_preprocessor_pragma_define_has_noarg(Define))
          tkreturn(TK_SUBSTITUTOR_NOARG)
        else if(adms_preprocessor_pragma_define_has_nullarg(Define))
          tkreturn(TK_SUBSTITUTOR_NULLARG_ALONE)
        else
          tkreturn(TK_SUBSTITUTOR_WITHARG_ALONE)
      }
      else
      {
         preprocessorlval.mystr = strdup(preprocessortext);
         pproot()->cr_scanner->cur_message=strdup(preprocessortext);
         tkreturn(TK_ERROR_PRAGMA_NOT_FOUND)
      }
    }
    else
      tkreturn(TK_IDENT)
  }

}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 761 "preprocessorLex.l"
{

  preprocessorlval.mystr = strdup(preprocessortext);
  tkreturn(TK_IDENT)

}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 768 "preprocessorLex.l"
{
  preprocessorlval.mystr = strdup(preprocessortext);
  return '(';
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 773 "preprocessorLex.l"
{
  preprocessorlval.mystr = strdup(preprocessortext);
  return ')';
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 778 "preprocessorLex.l"
{
  preprocessorlval.mystr = strdup(preprocessortext);
  return ',';
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 783 "preprocessorLex.l"
{
  preprocessorlval.mystr = strdup(preprocessortext);
  return TK_NOT_IDENT;
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(PRAGMA_PATH):
case YY_STATE_EOF(PRAGMA_COMMENT):
case YY_STATE_EOF(PRAGMA_NAME):
case YY_STATE_EOF(PRAGMA_ERROR):
case YY_STATE_EOF(PRAGMA_DEFINE_START):
case YY_STATE_EOF(PRAGMA_DEFINE_IGNORE):
case YY_STATE_EOF(PRAGMA_DEFINE_NOARG):
case YY_STATE_EOF(PRAGMA_DEFINE_WITHARG):
case YY_STATE_EOF(PRAGMA_DEFINE_TEXT_START):
case YY_STATE_EOF(PRAGMA_DEFINE_TEXT):
case YY_STATE_EOF(PRAGMA_DEFINE_WITHARG_COMMA):
case YY_STATE_EOF(PRAGMA_DEFINE_WITHARG_ARGS):
case YY_STATE_EOF(PRAGMA_SUBSTITUTOR_START):
case YY_STATE_EOF(PRAGMA_SUBSTITUTOR_ARG):
case YY_STATE_EOF(PRAGMA_SUBSTITUTOR_PAIR):
case YY_STATE_EOF(PRAGMA_SUBSTITUTOR_ARGITEM):
case YY_STATE_EOF(PRAGMA_SUBSTITUTOR_ARGCOMMA):
case YY_STATE_EOF(PRAGMA_SUBSTITUTOR_ARGEND):
#line 788 "preprocessorLex.l"
{
  char* string=NULL;
  if( pproot()->Scanner != NULL )
    {
      preprocessor_delete_buffer((YY_BUFFER_STATE)(pproot()->cr_scanner->buffer));
      free(pproot()->cr_scanner );
      pproot()->cr_scanner = (p_preprocessor) adms_slist_pull(&pproot()->Scanner );
      preprocessorin = pproot()->cr_scanner->fid;
      preprocessor_switch_to_buffer((YY_BUFFER_STATE)pproot()->cr_scanner->buffer );
    }
  else
    yyterminate ();
  adms_k2strconcat(&string,"# ");
  adms_strconcat(&string,adms_integertostring(pproot()->cr_scanner->cur_line_position+1));
  adms_k2strconcat(&string," \"");
  adms_k2strconcat(&string,pproot()->cr_scanner->filename);
  adms_k2strconcat(&string,"\"");
  preprocessorlval.mystr=string;
  tkreturn(TK_EOF)
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 809 "preprocessorLex.l"
ECHO;
	YY_BREAK
#line 2221 "preprocessorLex.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed preprocessorin at a new source and called
			 * preprocessorlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = preprocessorin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( preprocessorwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * preprocessortext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of preprocessorlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			preprocessorrestart(preprocessorin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) preprocessorrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 294 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 294 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 293);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up preprocessortext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					preprocessorrestart(preprocessorin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( preprocessorwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve preprocessortext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void preprocessorrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        preprocessorensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            preprocessor_create_buffer(preprocessorin,YY_BUF_SIZE );
	}

	preprocessor_init_buffer(YY_CURRENT_BUFFER,input_file );
	preprocessor_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void preprocessor_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		preprocessorpop_buffer_state();
	 *		preprocessorpush_buffer_state(new_buffer);
     */
	preprocessorensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	preprocessor_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (preprocessorwrap()) processing, but the only time this flag
	 * is looked at is after preprocessorwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void preprocessor_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	preprocessorin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE preprocessor_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) preprocessoralloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in preprocessor_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) preprocessoralloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in preprocessor_create_buffer()" );

	b->yy_is_our_buffer = 1;

	preprocessor_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with preprocessor_create_buffer()
 * 
 */
    void preprocessor_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		preprocessorfree((void *) b->yy_ch_buf  );

	preprocessorfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a preprocessorrestart() or at EOF.
 */
    static void preprocessor_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	preprocessor_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then preprocessor_init_buffer was _probably_
     * called from preprocessorrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void preprocessor_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		preprocessor_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void preprocessorpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	preprocessorensure_buffer_stack();

	/* This block is copied from preprocessor_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from preprocessor_switch_to_buffer. */
	preprocessor_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void preprocessorpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	preprocessor_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		preprocessor_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void preprocessorensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)preprocessoralloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in preprocessorensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)preprocessorrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in preprocessorensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE preprocessor_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) preprocessoralloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in preprocessor_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	preprocessor_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to preprocessorlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       preprocessor_scan_bytes() instead.
 */
YY_BUFFER_STATE preprocessor_scan_string (yyconst char * yystr )
{
    
	return preprocessor_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to preprocessorlex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE preprocessor_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) preprocessoralloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in preprocessor_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = preprocessor_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in preprocessor_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up preprocessortext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		preprocessortext[preprocessorleng] = (yy_hold_char); \
		(yy_c_buf_p) = preprocessortext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		preprocessorleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int preprocessorget_lineno  (void)
{
        
    return preprocessorlineno;
}

/** Get the input stream.
 * 
 */
FILE *preprocessorget_in  (void)
{
        return preprocessorin;
}

/** Get the output stream.
 * 
 */
FILE *preprocessorget_out  (void)
{
        return preprocessorout;
}

/** Get the length of the current token.
 * 
 */
int preprocessorget_leng  (void)
{
        return preprocessorleng;
}

/** Get the current token.
 * 
 */

char *preprocessorget_text  (void)
{
        return preprocessortext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void preprocessorset_lineno (int  line_number )
{
    
    preprocessorlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see preprocessor_switch_to_buffer
 */
void preprocessorset_in (FILE *  in_str )
{
        preprocessorin = in_str ;
}

void preprocessorset_out (FILE *  out_str )
{
        preprocessorout = out_str ;
}

int preprocessorget_debug  (void)
{
        return preprocessor_flex_debug;
}

void preprocessorset_debug (int  bdebug )
{
        preprocessor_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from preprocessorlex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    preprocessorin = stdin;
    preprocessorout = stdout;
#else
    preprocessorin = (FILE *) 0;
    preprocessorout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * preprocessorlex_init()
     */
    return 0;
}

/* preprocessorlex_destroy is for both reentrant and non-reentrant scanners. */
int preprocessorlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		preprocessor_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		preprocessorpop_buffer_state();
	}

	/* Destroy the stack itself. */
	preprocessorfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    preprocessorfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * preprocessorlex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *preprocessoralloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *preprocessorrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void preprocessorfree (void * ptr )
{
	free( (char *) ptr );	/* see preprocessorrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 809 "preprocessorLex.l"


int preprocessorwrap (void) {return 1;}


