#line 2 "verilogaLex.c"

#line 4 "verilogaLex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer veriloga_create_buffer
#define yy_delete_buffer veriloga_delete_buffer
#define yy_flex_debug veriloga_flex_debug
#define yy_init_buffer veriloga_init_buffer
#define yy_flush_buffer veriloga_flush_buffer
#define yy_load_buffer_state veriloga_load_buffer_state
#define yy_switch_to_buffer veriloga_switch_to_buffer
#define yyin verilogain
#define yyleng verilogaleng
#define yylex verilogalex
#define yylineno verilogalineno
#define yyout verilogaout
#define yyrestart verilogarestart
#define yytext verilogatext
#define yywrap verilogawrap
#define yyalloc verilogaalloc
#define yyrealloc verilogarealloc
#define yyfree verilogafree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE verilogarestart(verilogain  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int verilogaleng;

extern FILE *verilogain, *verilogaout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up verilogatext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up verilogatext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via verilogarestart()), so that the user can continue scanning by
	 * just pointing verilogain at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when verilogatext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int verilogaleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow verilogawrap()'s to do buffer switches
 * instead of setting up a fresh verilogain.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void verilogarestart (FILE *input_file  );
void veriloga_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE veriloga_create_buffer (FILE *file,int size  );
void veriloga_delete_buffer (YY_BUFFER_STATE b  );
void veriloga_flush_buffer (YY_BUFFER_STATE b  );
void verilogapush_buffer_state (YY_BUFFER_STATE new_buffer  );
void verilogapop_buffer_state (void );

static void verilogaensure_buffer_stack (void );
static void veriloga_load_buffer_state (void );
static void veriloga_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER veriloga_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE veriloga_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE veriloga_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE veriloga_scan_bytes (yyconst char *bytes,int len  );

void *verilogaalloc (yy_size_t  );
void *verilogarealloc (void *,yy_size_t  );
void verilogafree (void *  );

#define yy_new_buffer veriloga_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        verilogaensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            veriloga_create_buffer(verilogain,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        verilogaensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            veriloga_create_buffer(verilogain,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *verilogain = (FILE *) 0, *verilogaout = (FILE *) 0;

typedef int yy_state_type;

extern int verilogalineno;

int verilogalineno = 1;

extern char *verilogatext;
#define yytext_ptr verilogatext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up verilogatext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	verilogaleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 74
#define YY_END_OF_BUFFER 75
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[310] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   75,   73,    3,    1,   73,   73,
       73,   73,   73,   73,   73,   69,   70,   73,   73,   61,
       61,   73,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   73,   73,   13,
       74,   13,   13,   15,   14,   17,   17,   74,   16,   19,
       19,   24,   21,   21,   24,   22,   24,    8,    7,    6,
        8,    8,    5,    3,    1,    0,    9,   67,   64,    0,
       68,   68,   10,   72,   72,   69,    0,    0,   70,   63,
       62,   61,   61,   66,   61,   61,   61,   61,   61,   61,

       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       47,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       65,    2,   11,    0,    0,    0,   14,    0,   16,   16,
        0,   18,   21,    0,   22,   20,   22,    0,    0,    0,
        7,    6,    0,    4,    5,   67,   10,    0,    0,   72,
       71,   60,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   46,   61,   61,   52,   61,   61,   61,   59,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
        0,    0,    0,    0,    0,   72,   61,   61,   61,   61,
       49,   61,   61,   61,   53,   61,   61,   61,   61,   61,

       61,   34,   57,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   55,   61,   61,    0,   12,    0,   23,
       61,   61,   45,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   42,   40,   61,   61,   61,
       61,   61,   61,   61,   48,   61,   44,   43,   61,   61,
       35,   61,   61,   61,   61,   61,   61,   61,   36,   61,
       28,   38,   41,   61,   61,   56,   61,   51,   61,   50,
       61,   61,   61,   61,   58,   61,   54,   61,   61,   61,
       61,   61,   61,   61,   61,   30,   61,   61,   61,   61,
       61,   61,   29,   39,   25,   33,   27,   32,   61,   61,

       61,   61,   31,   61,   61,   61,   37,   26,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    7,    1,    8,    9,   10,
       11,   12,   13,   14,   13,   15,    1,   16,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,    1,   19,
       20,   21,   22,    1,   23,   23,   23,   23,   24,   25,
       26,   26,   27,   26,   26,   26,   26,   28,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   29,   26,   26,
        1,    1,    1,   30,   26,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   26,   26,   40,   41,   42,
       43,   44,   26,   45,   46,   47,   48,   26,   49,   50,
       26,   26,    1,   51,    1,   52,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[53] =
    {   0,
        1,    2,    2,    2,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    4,    3,    1,    2,
        1,    2,    5,    5,    5,    6,    6,    6,    6,    1,
        5,    5,    5,    5,    5,    5,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        1,    1
    } ;

static yyconst flex_int16_t yy_base[326] =
    {   0,
        0,  678,   52,    0,  104,    0,  155,  158,  160,  161,
      180,    0,  231,  235,  683,  685,  680,  685,  678,  675,
        0,  671,  164,  666,  152,  226,  229,  658,  655,    0,
      647,  622,  130,  212,  642,  219,  209,  131,  627,  224,
      628,  639,  621,  225,  633,  620,  628,  614,  662,  685,
      685,  652,  267,  685,    0,  685,  270,  275,  278,  685,
      657,  685,  282,  299,  650,  303,  306,  685,  658,  685,
      656,  653,  282,  655,  685,  651,  685,    0,  685,  309,
      311,  685,  313,  306,  315,  321,  327,    0,  331,  685,
      685,    0,  630,  685,  615,  622,  615,  620,  604,  613,

      602,  606,  600,  611,  611,  600,  597,  598,  598,  596,
        0,  315,  604,  590,  589,  590,  587,  602,  587,  592,
      685,  628,  685,  350,  361,  371,    0,  365,  375,  386,
      624,  685,  392,  617,  396,  685,  399,  407,  413,  420,
      625,  685,  621,  685,  317,    0,  428,  344,  375,  396,
        0,    0,  594,  584,  584,  580,  586,  589,  586,  587,
      582,  403,  576,  566,    0,  573,  580,  564,    0,  563,
      562,  574,  560,  559,  562,  574,  569,  563,  563,  561,
      444,  595,  449,  594,  403,  424,  552,  554,  554,  562,
        0,  546,  554,  553,    0,  560,  551,  541,  545,  556,

      538,    0,    0,  538,  542,  536,  535,  544,  540,  534,
      530,  536,  534,    0,  533,  539,  568,  685,  567,  685,
      527,  533,    0,  531,  528,  523,  524,  519,  518,  521,
      528,  514,  526,  520,  524,    0,    0,  522,  521,  520,
      507,  518,  505,  514,    0,  519,    0,    0,  423,  429,
        0,  433,  434,  432,  416,  415,  427,  418,    0,  415,
        0,    0,    0,  412,  419,    0,  412,    0,  417,    0,
      416,  396,  398,  389,    0,  386,    0,  391,  376,  374,
      344,  340,  343,  345,  336,    0,  304,  302,  288,  292,
      284,  276,    0,    0,    0,    0,  258,    0,  252,  246,

      236,  233,    0,  232,  230,  218,    0,    0,  685,  471,
      477,  483,  489,  491,  497,  500,  505,  509,  515,  520,
      526,  529,  532,  537,  543
    } ;

static yyconst flex_int16_t yy_def[326] =
    {   0,
      309,    1,  309,    3,  309,    5,  310,  310,  311,  311,
      309,   11,  312,  312,  309,  309,  309,  309,  309,  313,
      314,  309,  315,  309,  309,  309,  309,  309,  309,  316,
      316,  309,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  309,  309,  309,
      309,  309,  317,  309,  318,  309,  309,  309,  309,  309,
      319,  309,  309,  309,  309,  309,  320,  309,  309,  309,
      309,  321,  309,  309,  309,  313,  309,  322,  309,  315,
      315,  309,  309,  309,  309,  309,  309,  323,  309,  309,
      309,  316,  316,  309,  316,  316,  316,  316,  316,  316,

      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      309,  309,  309,  309,  317,  309,  318,  309,  309,  309,
      319,  309,  309,  309,  309,  309,  309,  309,  320,  309,
      309,  309,  321,  309,  309,  322,  309,  309,  309,  309,
      323,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      309,  324,  309,  325,  309,  309,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,

      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  324,  309,  325,  309,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,

      316,  316,  316,  316,  316,  316,  316,  316,    0,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309
    } ;

static yyconst flex_int16_t yy_nxt[738] =
    {   0,
       16,   17,   18,   19,   20,   16,   21,   22,   23,   24,
       16,   16,   16,   16,   25,   26,   27,   16,   28,   16,
       29,   16,   30,   30,   30,   30,   31,   30,   30,   32,
       33,   34,   35,   36,   37,   38,   39,   30,   40,   30,
       41,   42,   43,   44,   45,   46,   30,   30,   47,   30,
       48,   16,   50,   50,   51,   50,   50,   50,   50,   50,
       50,   50,   50,   52,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   53,   53,   53,   53,   53,   53,
       53,   50,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,

       53,   53,   50,   50,   54,   54,   51,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   55,   55,   55,   55,
       55,   55,   55,   54,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   54,   54,   57,   58,   57,   57,
       58,   57,   51,   51,   61,   61,   81,   84,   84,   95,
      106,   96,   82,  107,   59,  108,   57,   59,  109,   57,
       62,   63,   64,   63,   62,   62,   62,   62,   62,   62,
       62,   65,   62,   66,   62,   62,   62,   62,   62,   62,

       62,   63,   67,   67,   67,   67,   67,   67,   67,   62,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       62,   62,   69,   70,   71,   72,   69,   70,   71,   72,
       85,   86,   86,   85,   89,   89,   97,   73,  103,   87,
      104,   73,   87,  100,   88,  116,   98,  101,  105,  111,
       87,  102,  308,   87,  307,  112,  306,  117,  124,  124,
      124,  128,  128,  128,  305,   88,  128,  128,  128,  130,
      130,  130,  304,  133,  133,  133,  126,  303,  124,  129,
      302,  128,  301,  134,  129,  135,  128,  145,  145,  130,

      133,  133,  133,  133,  137,  137,  137,  138,  138,  138,
      134,   81,  135,   81,  147,  147,  147,   82,  300,   82,
      133,   84,   84,  299,  137,  140,  298,  138,  297,  148,
       84,   84,  145,  145,  147,   85,   86,   86,   87,  149,
      148,  296,  150,  150,   87,   85,   89,   89,  295,   87,
      169,  124,  124,  124,   87,   87,  185,  170,  171,  186,
      186,  172,  124,  124,  124,   87,  128,  128,  128,  126,
      294,  124,  181,  181,  181,  182,  130,  130,  130,  293,
      126,  292,  124,  291,  129,  290,  128,  130,  130,  130,
      150,  150,  181,  133,  133,  133,  130,  137,  137,  137,

      137,  137,  137,  134,  289,  135,  288,  130,  138,  138,
      138,  150,  150,  133,  138,  138,  138,  137,  186,  186,
      137,  183,  183,  183,  184,  287,  140,  286,  138,  147,
      147,  147,  140,  285,  138,  196,  197,  284,  198,  186,
      186,  183,  283,  199,  200,  181,  181,  181,  182,  147,
      183,  183,  183,  184,  282,  281,  280,  279,  278,  277,
      276,  275,  274,  273,  272,  181,  271,  270,  269,  268,
      183,   56,   56,   56,   56,   56,   56,   60,   60,   60,
       60,   60,   60,   68,   68,   68,   68,   68,   68,   76,
       76,   76,   76,   76,   76,   78,   78,   80,   80,   80,

       80,   80,   80,   92,   92,   92,  125,  125,  125,  125,
      125,  127,  127,  127,  127,  131,  131,  131,  131,  131,
      131,  139,  139,  139,  139,  139,  143,  143,  143,  143,
      143,  143,  146,  146,  146,  151,  151,  217,  217,  217,
      217,  217,  217,  219,  219,  219,  219,  219,  219,  267,
      266,  265,  264,  263,  262,  261,  260,  259,  258,  257,
      256,  255,  254,  253,  252,  251,  250,  249,  248,  247,
      246,  220,  218,  245,  244,  243,  242,  241,  240,  239,
      238,  237,  236,  235,  234,  233,  232,  231,  230,  229,
      228,  227,  226,  225,  224,  223,  222,  221,  220,  218,

      216,  215,  214,  213,  212,  211,  210,  209,  208,  207,
      206,  205,  204,  203,  202,  201,  195,  194,  193,  192,
      191,  190,  189,  188,  187,  144,  141,  136,  132,  122,
      180,  179,  178,  177,  176,  175,  174,  173,  168,  167,
      166,  165,  164,  163,  162,  161,  160,  159,  158,  157,
      156,  155,  154,  153,  152,   77,   74,  144,  142,  141,
      136,  132,  123,  122,  121,  120,  119,  118,  115,  114,
      113,  110,   99,   94,   93,   91,   90,   83,   79,   77,
       75,   74,  309,   49,   15,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,

      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309
    } ;

static yyconst flex_int16_t yy_chk[738] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    7,    7,    7,    8,
        8,    8,    9,   10,    9,   10,   23,   25,   25,   33,
       38,   33,   23,   38,    7,   38,    7,    8,   38,    8,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,

       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   13,   13,   13,   13,   14,   14,   14,   14,
       26,   26,   26,   27,   27,   27,   34,   13,   37,   26,
       37,   14,   27,   36,   26,   44,   34,   36,   37,   40,
       26,   36,  306,   27,  305,   40,  304,   44,   53,   53,
       53,   57,   57,   57,  302,   26,   58,   58,   58,   59,
       59,   59,  301,   63,   63,   63,   53,  300,   53,   57,
      299,   57,  297,   63,   58,   63,   58,   73,   73,   59,

       64,   64,   64,   63,   66,   66,   66,   67,   67,   67,
       64,   80,   64,   81,   83,   83,   83,   80,  292,   81,
       64,   84,   84,  291,   66,   67,  290,   67,  289,   84,
       85,   85,  145,  145,   83,   86,   86,   86,   85,   87,
       84,  288,   87,   87,   86,   89,   89,   89,  287,   85,
      112,  124,  124,  124,   89,   86,  148,  112,  112,  148,
      148,  112,  125,  125,  125,   89,  128,  128,  128,  124,
      285,  124,  126,  126,  126,  126,  129,  129,  129,  284,
      125,  283,  125,  282,  128,  281,  128,  130,  130,  130,
      149,  149,  126,  133,  133,  133,  129,  135,  135,  135,

      137,  137,  137,  133,  280,  133,  279,  130,  138,  138,
      138,  150,  150,  133,  139,  139,  139,  135,  185,  185,
      137,  140,  140,  140,  140,  278,  138,  276,  138,  147,
      147,  147,  139,  274,  139,  162,  162,  273,  162,  186,
      186,  140,  272,  162,  162,  181,  181,  181,  181,  147,
      183,  183,  183,  183,  271,  269,  267,  265,  264,  260,
      258,  257,  256,  255,  254,  181,  253,  252,  250,  249,
      183,  310,  310,  310,  310,  310,  310,  311,  311,  311,
      311,  311,  311,  312,  312,  312,  312,  312,  312,  313,
      313,  313,  313,  313,  313,  314,  314,  315,  315,  315,

      315,  315,  315,  316,  316,  316,  317,  317,  317,  317,
      317,  318,  318,  318,  318,  319,  319,  319,  319,  319,
      319,  320,  320,  320,  320,  320,  321,  321,  321,  321,
      321,  321,  322,  322,  322,  323,  323,  324,  324,  324,
      324,  324,  324,  325,  325,  325,  325,  325,  325,  246,
      244,  243,  242,  241,  240,  239,  238,  235,  234,  233,
      232,  231,  230,  229,  228,  227,  226,  225,  224,  222,
      221,  219,  217,  216,  215,  213,  212,  211,  210,  209,
      208,  207,  206,  205,  204,  201,  200,  199,  198,  197,
      196,  194,  193,  192,  190,  189,  188,  187,  184,  182,

      180,  179,  178,  177,  176,  175,  174,  173,  172,  171,
      170,  168,  167,  166,  164,  163,  161,  160,  159,  158,
      157,  156,  155,  154,  153,  143,  141,  134,  131,  122,
      120,  119,  118,  117,  116,  115,  114,  113,  110,  109,
      108,  107,  106,  105,  104,  103,  102,  101,  100,   99,
       98,   97,   96,   95,   93,   76,   74,   72,   71,   69,
       65,   61,   52,   49,   48,   47,   46,   45,   43,   42,
       41,   39,   35,   32,   31,   29,   28,   24,   22,   20,
       19,   17,   15,    2,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,

      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int veriloga_flex_debug;
int veriloga_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *verilogatext;
#line 1 "verilogaLex.l"
#line 2 "verilogaLex.l"

#include "admsVeriloga.h"
#include "verilogaYacc.h"

static int adms_strtointeger (const char *mystr)
{
  int val;
  errno=0;
  val=(int)strtol(mystr,NULL,10);
  if(errno)
    adms_message_fatal(("%s: strtoint conversion failed\n",mystr))
  return val;
}
void adms_veriloga_setfile_input (FILE *ifile)
{
  verilogain=ifile;
}
void verilogaerror (const char *s)
{
  adms_message_fatal(("%s: during lexical analysis %s at line %i -- see '%s'\n",root()->_curfilename,s,root()->_curline,verilogatext))
}
void POS_UPDATE(const int myyyleng,const char*myyytext)
{
  int c=root()->_fpos;
  adms_message_dbg_vla(("%s:%i:%i-%i read token '%s'\n",root()->_curfilename,
    root()->_curline,c+1,c+myyyleng,myyytext))
  adms_admsmain_valueto_fpos(root(),c+myyyleng);
}
void TKRETURN(const char*myyytext, const int myyyleng)
{
  verilogalval._lexval=adms_lexval_new(myyytext,root()->_curfilename,root()->_curline,root()->_fpos+1);
  POS_UPDATE(myyyleng,myyytext);
}
void NL(const int i)
{
  adms_admsmain_valueto_curline(root(),root()->_curline+i);
  adms_admsmain_valueto_fpos(root(),0);
}
void NLcheck(const char*myyytext)
{
  const char*s=myyytext;
  while(*s)
  {
    if(*s=='\r' && *s && *s=='\n') NL(1),s++;
    else if(*s=='\n' || *s=='\r') NL(1);
    s++;
  }
}
void TKSTRIPPEDRETURN(const char*myyytext, const int myyyleng)
{
  char*mystrippedstring;
  int mynewlen=strlen(myyytext)-2;
  assert(mynewlen>=0);
  mystrippedstring=(char*)malloc(mynewlen+1);
  if(mystrippedstring)
  {
    strncpy(mystrippedstring,myyytext+1,mynewlen);
    mystrippedstring[mynewlen]='\0';
  }
  POS_UPDATE(myyyleng,myyytext);
  verilogalval._lexval=adms_lexval_new(
    mystrippedstring,
    root()->_curfilename,
    root()->_curline,
    root()->_fpos
  );
  free(mystrippedstring);
}
#ifdef YYDEBUG
extern int yydebug;
#endif

 
 
 
 
 
 
#line 816 "verilogaLex.c"

#define INITIAL 0
#define insideAttribute 1
#define insideAttributeBegin 2
#define insideAttributeEqual 3
#define insideAttributeValue 4
#define insideAttributeEnd 5
#define insidePragma 6

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int verilogalex_destroy (void );

int verilogaget_debug (void );

void verilogaset_debug (int debug_flag  );

YY_EXTRA_TYPE verilogaget_extra (void );

void verilogaset_extra (YY_EXTRA_TYPE user_defined  );

FILE *verilogaget_in (void );

void verilogaset_in  (FILE * in_str  );

FILE *verilogaget_out (void );

void verilogaset_out  (FILE * out_str  );

int verilogaget_leng (void );

char *verilogaget_text (void );

int verilogaget_lineno (void );

void verilogaset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int verilogawrap (void );
#else
extern int verilogawrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( verilogatext, verilogaleng, 1, verilogaout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( verilogain )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( verilogain ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, verilogain))==0 && ferror(verilogain)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(verilogain); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int verilogalex (void);

#define YY_DECL int verilogalex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after verilogatext and verilogaleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( verilogaleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(verilogatext[verilogaleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 100 "verilogaLex.l"


#line 1008 "verilogaLex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! verilogain )
			verilogain = stdin;

		if ( ! verilogaout )
			verilogaout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			verilogaensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				veriloga_create_buffer(verilogain,YY_BUF_SIZE );
		}

		veriloga_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of verilogatext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 310 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 685 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 102 "verilogaLex.l"
{NL(1);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 104 "verilogaLex.l"
{BEGIN(insidePragma);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 105 "verilogaLex.l"
{POS_UPDATE(verilogaleng,verilogatext);}
	YY_BREAK

case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 108 "verilogaLex.l"
{
  char*mystrippedstring;
  int mynewlen=strlen(verilogatext)-2;
  assert(mynewlen>=0);
  mystrippedstring=(char*)malloc(mynewlen+1);
  if(mystrippedstring)
  {
    strncpy(mystrippedstring,verilogatext+1,mynewlen);
    mystrippedstring[mynewlen]='\0';
  }
  adms_admsmain_valueto_curfilename(root(),mystrippedstring);
  free(mystrippedstring);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 121 "verilogaLex.l"
{NL(adms_strtointeger(verilogatext));}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 122 "verilogaLex.l"
{
  BEGIN(INITIAL);
  adms_admsmain_valueto_fpos(root(),0);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 126 "verilogaLex.l"
{POS_UPDATE(verilogaleng,verilogatext);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 127 "verilogaLex.l"
{
  adms_message_fatal(("[%s:%i]: inside pragma declaration unexpected character at [%s]\n",root()->_curfilename,root()->_curline,verilogatext))
}
	YY_BREAK

case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 132 "verilogaLex.l"
{TKSTRIPPEDRETURN(verilogatext,verilogaleng); return tk_anystring;}
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 134 "verilogaLex.l"
{NLcheck(verilogatext);BEGIN(insideAttribute); {TKRETURN(verilogatext,verilogaleng); return tk_beginattribute;}}
	YY_BREAK

case 11:
YY_RULE_SETUP
#line 137 "verilogaLex.l"
{BEGIN(INITIAL);TKRETURN(verilogatext,verilogaleng);return tk_endattribute;}
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 138 "verilogaLex.l"
{BEGIN(insideAttributeBegin);yyless(0);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 139 "verilogaLex.l"
{
    char myyytext[1000];
    register int i=0;
    myyytext[i]=verilogatext[0];
    for(;;)
    {
      while((myyytext[i]!='*')&&(myyytext[i]!=EOF))
      {
        myyytext[++i]=input();
      }
      if(myyytext[i]=='*')
      {
        while((myyytext[++i]=input())=='*')
        ;
        if(myyytext[i]==')')
        {
          BEGIN(INITIAL);
          i-=2;
          while(myyytext[i]==' ')
            i--;
          myyytext[i+1]='\0';
          POS_UPDATE(verilogaleng,verilogatext);
          verilogalval._lexval=adms_lexval_new(
            myyytext,
            root()->_curfilename,
            root()->_curline,
            root()->_fpos
          );
          return tk_anytext;
        }
      }
      if(myyytext[i]==EOF)
      {
        adms_message_fatal(("[%s:%i]: inside Verilog-ams EOF found in attribute declaration [%s]\n",root()->_curfilename,root()->_curline,verilogatext))
      }
    }
}
	YY_BREAK


case 14:
YY_RULE_SETUP
#line 178 "verilogaLex.l"
{BEGIN(insideAttributeEqual);TKRETURN(verilogatext,verilogaleng);return tk_ident;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 179 "verilogaLex.l"
{
  adms_message_fatal(("[%s:%i]: inside Verilog-ams attribute declaration unexpected character at [%s]\n",root()->_curfilename,root()->_curline,verilogatext))
}
	YY_BREAK


case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 184 "verilogaLex.l"
{NLcheck(verilogatext);BEGIN(insideAttributeValue);return '=';}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 185 "verilogaLex.l"
{
  adms_message_fatal(("[%s:%i]: inside Verilog-ams attribute declaration unexpected character at [%s]\n",root()->_curfilename,root()->_curline,verilogatext))
}
	YY_BREAK


case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 190 "verilogaLex.l"
{TKSTRIPPEDRETURN(verilogatext,verilogaleng);BEGIN(insideAttributeEnd);return tk_anystring;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 191 "verilogaLex.l"
{
  adms_message_fatal(("[%s:%i]: inside Verilog-ams attribute declaration unexpected character at [%s]\n",root()->_curfilename,root()->_curline,verilogatext))
}
	YY_BREAK


case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 196 "verilogaLex.l"
{NLcheck(verilogatext); BEGIN(INITIAL);POS_UPDATE(verilogaleng,verilogatext);TKRETURN(verilogatext,verilogaleng);return tk_endattribute;}
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 197 "verilogaLex.l"
{NLcheck(verilogatext); BEGIN(insideAttributeBegin);POS_UPDATE(verilogaleng,verilogatext);}
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 198 "verilogaLex.l"
{NLcheck(verilogatext); BEGIN(insideAttributeBegin);POS_UPDATE(verilogaleng,verilogatext);}
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 199 "verilogaLex.l"
{BEGIN(insideAttributeBegin);yyless(0);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 200 "verilogaLex.l"
{
  adms_message_fatal(("[%s:%i]: inside Verilog-ams attribute declaration unexpected character at [%s]\n",root()->_curfilename,root()->_curline,verilogatext))
}
	YY_BREAK

case 25:
YY_RULE_SETUP
#line 205 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_parameter;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 206 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_aliasparameter;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 207 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_aliasparam;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 208 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_module;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 209 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_endmodule;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 210 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_function;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 211 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_endfunction;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 212 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_discipline;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 213 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_potential;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 214 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_flow;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 215 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_domain;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 216 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_ground;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 217 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_enddiscipline;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 218 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_nature;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 219 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_endnature;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 220 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_input;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 221 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_output;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 222 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_inout;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 223 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_branch;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 224 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_analog;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 225 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_begin;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 226 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_end;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 227 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_if;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 228 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_while;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 229 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_case;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 230 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_endcase;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 231 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_default;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 232 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_for;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 233 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_else;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 234 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_integer;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 235 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_real;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 236 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_string;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 237 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_from;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 238 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_exclude;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 239 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_inf;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 240 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_inf;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 242 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_ident;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 244 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_op_shr;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 245 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_op_shl;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 246 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_and;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 247 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_or;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 248 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_bitwise_equr;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 250 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_dollar_ident;}
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 251 "verilogaLex.l"
{TKSTRIPPEDRETURN(verilogatext,verilogaleng); return tk_char;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 252 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_integer;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 253 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_integer;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 254 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_integer;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 255 "verilogaLex.l"
{TKRETURN(verilogatext,verilogaleng); return tk_number;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 257 "verilogaLex.l"
{POS_UPDATE(verilogaleng,verilogatext);return verilogatext[0];}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 259 "verilogaLex.l"
ECHO;
	YY_BREAK
#line 1548 "verilogaLex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(insideAttribute):
case YY_STATE_EOF(insideAttributeBegin):
case YY_STATE_EOF(insideAttributeEqual):
case YY_STATE_EOF(insideAttributeValue):
case YY_STATE_EOF(insideAttributeEnd):
case YY_STATE_EOF(insidePragma):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed verilogain at a new source and called
			 * verilogalex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = verilogain;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( verilogawrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * verilogatext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of verilogalex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					verilogarealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			verilogarestart(verilogain  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) verilogarealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 310 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 310 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 309);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					verilogarestart(verilogain );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( verilogawrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve verilogatext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void verilogarestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        verilogaensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            veriloga_create_buffer(verilogain,YY_BUF_SIZE );
	}

	veriloga_init_buffer(YY_CURRENT_BUFFER,input_file );
	veriloga_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void veriloga_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		verilogapop_buffer_state();
	 *		verilogapush_buffer_state(new_buffer);
     */
	verilogaensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	veriloga_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (verilogawrap()) processing, but the only time this flag
	 * is looked at is after verilogawrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void veriloga_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	verilogain = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE veriloga_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) verilogaalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in veriloga_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) verilogaalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in veriloga_create_buffer()" );

	b->yy_is_our_buffer = 1;

	veriloga_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with veriloga_create_buffer()
 * 
 */
    void veriloga_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		verilogafree((void *) b->yy_ch_buf  );

	verilogafree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a verilogarestart() or at EOF.
 */
    static void veriloga_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	veriloga_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then veriloga_init_buffer was _probably_
     * called from verilogarestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void veriloga_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		veriloga_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void verilogapush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	verilogaensure_buffer_stack();

	/* This block is copied from veriloga_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from veriloga_switch_to_buffer. */
	veriloga_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void verilogapop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	veriloga_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		veriloga_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void verilogaensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)verilogaalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in verilogaensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)verilogarealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in verilogaensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE veriloga_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) verilogaalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in veriloga_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	veriloga_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to verilogalex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       veriloga_scan_bytes() instead.
 */
YY_BUFFER_STATE veriloga_scan_string (yyconst char * yystr )
{
    
	return veriloga_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to verilogalex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE veriloga_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) verilogaalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in veriloga_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = veriloga_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in veriloga_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up verilogatext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		verilogatext[verilogaleng] = (yy_hold_char); \
		(yy_c_buf_p) = verilogatext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		verilogaleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int verilogaget_lineno  (void)
{
        
    return verilogalineno;
}

/** Get the input stream.
 * 
 */
FILE *verilogaget_in  (void)
{
        return verilogain;
}

/** Get the output stream.
 * 
 */
FILE *verilogaget_out  (void)
{
        return verilogaout;
}

/** Get the length of the current token.
 * 
 */
int verilogaget_leng  (void)
{
        return verilogaleng;
}

/** Get the current token.
 * 
 */

char *verilogaget_text  (void)
{
        return verilogatext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void verilogaset_lineno (int  line_number )
{
    
    verilogalineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see veriloga_switch_to_buffer
 */
void verilogaset_in (FILE *  in_str )
{
        verilogain = in_str ;
}

void verilogaset_out (FILE *  out_str )
{
        verilogaout = out_str ;
}

int verilogaget_debug  (void)
{
        return veriloga_flex_debug;
}

void verilogaset_debug (int  bdebug )
{
        veriloga_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from verilogalex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    verilogain = stdin;
    verilogaout = stdout;
#else
    verilogain = (FILE *) 0;
    verilogaout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * verilogalex_init()
     */
    return 0;
}

/* verilogalex_destroy is for both reentrant and non-reentrant scanners. */
int verilogalex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		veriloga_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		verilogapop_buffer_state();
	}

	/* Destroy the stack itself. */
	verilogafree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * verilogalex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *verilogaalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *verilogarealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void verilogafree (void * ptr )
{
	free( (char *) ptr );	/* see verilogarealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 259 "verilogaLex.l"



int verilogawrap (void) {return 1;}

