.TH QucsAttenuator "1" "July 2006" "Debian/GNU Linux" "User Commands"
.SH NAME
QucsAttenuator \- An attenuator synthesis application.
.SH SYNOPSIS
.B qucsattenuator
[\fIOPTION\fR] ...
.SH DESCRIPTION

\fBQucs\fR is an integrated circuit simulator which means you will be
able to setup a circuit with a graphical user interface (GUI) and
simulate the large-signal, small-signal and noise behaviour of the
circuit.  After that simulation has finished you will be able to
present the simulation results on a presentation page or window.

The software aims to support all kinds of circuit simulation types,
e.g. DC, AC, S-parameter, harmonic balance analysis, noise analysis,
etc.

\fBQucsAttenuator\fR is the attenuator synthesis tool used by Qucs.
By use of an input dialog the user can create an attenuator which is
then copied into the system-wide clipboard.  In \fBQucs\fR the user
opens an empty schematic and presses CTRL-V (paste from
clipboard). The attenuator schematic is now inserted and can be
simulated.

Available attenuator topologies types are: Tee, Pi and Bridged-Tee.

.SH AVAILABILITY
The latest version of Qucs can always be obtained from
\fBwww.sourceforge.net\fR or \fBwww.freshmeat.net\fR
.SH "REPORTING BUGS"
Known bugs are documented within the BUGS file.  Report bugs to
<qucs-bugs@lists.sourceforge.net>.
.SH COPYRIGHT
Copyright \(co 2006 Michael Margraf <michael.margraf@alumni.tu-berlin.de>
.PP
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH AUTHORS
Written by Toyoyuki Ishikawa <toyoishi@gmail.com> and Michael
Margraf <michael.margraf@alumni.tu-berlin.de>.
