.TH admsXml "1" "September 2008" "Debian/GNU Linux" "User Commands"
.SH NAME
admsXml \- An automatic device model synthesizer.
.SH SYNOPSIS
.B admsXml
source [\fIOPTIONS\fR] \fB\-e\fR script1 [\-e script2 ...]
.SH DESCRIPTION
admsXml is a code generator that converts electrical compact
device models specified in high-level description language
into ready-to-compile c code for the API of spice simulators.
.SH FILES
.TP
\fR source
verilog\-ams source code
.TP
\fR script1, ...
admst scripts (xml format)
.SH OPTIONS
.TP
\fB\-D\fR NAME
predefine NAME as a macro, with definition `1'
.TP
\fB\-D\fR NAME=DEFINITION
predefine NAME as a macro, with definition DEFINITION
.TP
\fB\-I\fR DIR
Add directory DIR to search path for header files
.TP
\fB\-x\fR
ignore file .adms.implicit.xml
.TP
\fB\-xv\fR
do not check version number of scripts
.TP
\fB\-i\fR, \fB\-\-info\fR
miscellaneous info (release, web site, mailing list)
.TP
\fB\-v\fR, \fB\-\-version\fR
version number
.TP
\fB\-h\fR, \fB\-\-help\fR
short help
.SH ENVIRONMENT VARIABLES
.TP
\- adms_info="yes"|"no"
print info [default=yes]
.TP
\- adms_usage="yes"|"no"
print usage [default=yes]
.TP
\- adms_verbose="yes"|"no"
print messages [default=no]
.TP
\- adms_debug="yes"|"no"
print more messages [default=no]
.TP
\- adms_dbg_vla="yes"|"no"
debug messages during vla parsing [default=no]
.TP
\- adms_dbg_xml="yes"|"no"
debug messages during xml parsing [default=no]
.TP
\- adms_dbg_pre="yes"|"no"
debug messages during vla preprocessing [default=no]
.SH AVAILABILITY
The latest version of admsXml can always be obtained from \fBmot-adms.sourceforge.net\fR
.SH "REPORTING BUGS"
Known bugs are documented within the BUGS file.  Report bugs to
<r29173@users.sourceforge.net>.
.SH COPYRIGHT
.PP
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH AUTHORS
Written by Laurent Lemaitre <r29173@users.sourceforge.net>.
