.TH QucsVeri "1" "March 2007" "Debian/GNU Linux" "User Commands"
.SH NAME
QucsVeri \- A wrapper script for digital simulations.
.SH SYNOPSIS
.B qucsveri
[\fIOPTION\fR] \fIinfile\fR \fIoutfile\fR \fItime\fR \fIdir\fR \fIbindir\fR
.SH DESCRIPTION

\fBQucs\fR is an integrated circuit simulator which means you are able
to setup a circuit with a graphical user interface (GUI) and simulate
the large-signal, small-signal and noise behaviour of the circuit.
After that simulation has finished you can view the simulation results
on a presentation page or window.

The software aims to support all kinds of circuit simulation types,
e.g. DC, AC, S-parameter, harmonic balance analysis, noise analysis,
etc.

\fBQucsVeri\fR is a wrapper script for digital simulations performed
by Qucs.  The program utilizes the \fBIcarus Verilog\fR compiler in
order to convert the Verilog output of Qucs into a \fBiverilog\fR
program.  This file is then executed using \fBvvp\fR and its VCD
output file is converted to a Qucs dataset.
.SH OPTIONS
.TP
\fR INFILE
the filename of the Verilog file to be simulated located in the
directory specified in \fIDIR\fR
.TP
\fR OUTFILE
the filename of the Qucs dataset file to be produced
.TP
\fR TIME
duration of the digital simulation
.TP
\fR DIR
the name of the directory where the simulation is going to be performed
.TP
\fR BINDIR
the location where the \fIqucsconv\fR program is installed
.SH AVAILABILITY
The latest version of Qucs can always be obtained from
\fBwww.sourceforge.net\fR or \fBwww.freshmeat.net\fR
.SH "REPORTING BUGS"
Known bugs are documented within the BUGS file.  Report bugs to
<qucs-bugs@lists.sourceforge.net>.
.SH COPYRIGHT
Copyright \(co 2007 Stefan Jahn <stefan@lkcc.org>
.PP
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH AUTHORS
Written by Michael Margraf <michael.margraf@alumni.tu-berlin.de> and
Stefan Jahn <stefan@lkcc.org>.
