#cmakedefine BINARYDIR "@BINARYDIR@"
#cmakedefine BITMAPDIR "@BITMAPDIR@"
#cmakedefine DOCDIR "@DOCDIR@"
#cmakedefine LANGUAGEDIR "@LANGUAGEDIR@"
#cmakedefine LIBRARYDIR "@LIBRARYDIR@"
#cmakedefine OCTAVEDIR "@OCTAVEDIR@"

#define PACKAGE_VERSION "@PROJECT_VERSION@"
#define PACKAGE_STRING "qucs @PROJECT_VERSION@"
