#! /bin/sh
#
# qucsdigi - wrapper script for digital simulation
#
# Copyright (C) 2005 Michael Margraf <michael.margraf@alumni.tu-berlin.de>
# Copyright (C) 2005, 2006, 2008, 2009 Stefan Jahn <stefan@lkcc.org>
# Copyright (C) 2005 Raimund Jacob <raimi@lkcc.org>
#
# This is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
# 
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this package; see the file COPYING.  If not, write to
# the Free Software Foundation, Inc., 51 Franklin Street - Fifth Floor,
# Boston, MA 02110-1301, USA.  
#

# Bail out on any error
set -e

# catch termination signal and kill all child processes
#trap 'kill 0; exit 0' SIGTERM

if [ "$#" != 6 ]; then
    if [ "$#" != 7 ]; then
        echo "Usage: $0 <netlist.txt> <output.dat> <time> <directory> <bindirectory> <vlibs> [<convoption>]"
        echo "Directory has to contain the file 'netlist.txt'."
        exit 1
    fi
    OPTION=$7
fi

NAME=$1
NAMEOUT=$2
TIME=$3
DIR=$4
BINDIR=$5
VLIBS=$6

if [ ! -d "$DIR" ]; then
    echo "$DIR: Not a directory"
    exit 1
fi

cd $DIR

if [ ! -f $NAME ]; then
    echo "$NAME: No such file"
    exit 1
fi

CXX=`freehdl-config --cxx`
CXXFLAGS=`freehdl-config --cxxflags`
LIBS=`freehdl-config --libtool`
IEEELIBS=`freehdl-config --ieee`
LDFLAGS=`freehdl-config --ldflags|sed -e 's/ @LDFLAGS@/\/freehdl/g'|sed -e 's/@LIBS@//g'`
LIBTOOL=`freehdl-config --linker`

cp $NAME digi.vhdl
NAME="digi"

echo -n "running C++ conversion..."
freehdl-v2cc -m $NAME._main_.cc -Lvhdl -o $NAME.cc $NAME.vhdl
echo " done."

echo -n "compiling functions..."
$CXX $CXXFLAGS -c $NAME.cc
echo " done."

echo -n "compiling main..."
$CXX $CXXFLAGS -c $NAME._main_.cc
echo " done."cd

echo -n "linking..."

LTFLAGS="--mode=link"

# on darwn glibtool asks for --tag=
if [ $LIBTOOL = "glibtool" ]; then
    LTFLAGS="$LTFLAGS --tag=CC"
fi
#$CXX -o $NAME $NAME._main_.o $NAME.o -L /usr/lib/freehdl -lfreehdl-kernel -lfreehdl-std -Lieee
$LIBTOOL $LTFLAGS $CXX $NAME._main_.o $NAME.o $LDFLAGS $VLIBS $LIBS $IEEELIBS -o $NAME
echo " done."

echo "simulating..."
./$NAME -q -cmd "dc -f $NAME.vcd -t 1 ps -q;d;run $TIME;q;" <&-
wait $!

echo -n "running VCD conversion..."
$BINDIR/qucsconv $OPTION -if vcd -of qucsdata -i $NAME.vcd -o $NAMEOUT
echo " done."

