#! /bin/sh
#
# qucsdigi - wrapper script for digital simulation
#
# Copyright (C) 2005 Michael Margraf <michael.margraf@alumni.tu-berlin.de>
# Copyright (C) 2005 Stefan Jahn <stefan@lkcc.org>
#
# This is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
# 
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this package; see the file COPYING.  If not, write to
# the Free Software Foundation, Inc., 51 Franklin Street - Fifth Floor,
# Boston, MA 02110-1301, USA.  
#

NAME=$1
TIME=$2
DIR=$3

CXX=`freehdl-config --cxx`
CXXFLAGS=`freehdl-config --cxxflags`
LIBS=`freehdl-config --libtool`
LDFLAGS=`freehdl-config --ldflags`

OLDDIR=$(pwd)
cd $DIR
#echo "$OLDDIR -> $DIR -> $(pwd)"
cp $NAME digi.vhdl
NAME="digi"

echo -n "converting..."
freehdl-v2cc -m $NAME._main_.cc -o $NAME.cc $NAME.vhdl 2>/dev/null
if [ $? != "0" ]; then
  exit 1
fi
echo " done."

echo -n "compiling functions..."
$CXX $CXXFLAGS -c $NAME.cc
if [ $? != "0" ]; then
  exit 1
fi
echo " done."

echo -n "compiling main..."
$CXX $CXXFLAGS -c $NAME._main_.cc
if [ $? != "0" ]; then
  exit 1
fi
echo " done."

echo -n "linking..."
freehdl-libtool --quiet --mode=link $CXX $NAME._main_.o $NAME.o $LIBS -o $NAME
if [ $? != "0" ]; then
  exit 1
fi
echo " done."

echo -n "simulating..."
./$NAME -cmd "dc -f $NAME.vcd -q;d;run $TIME;q;" >/dev/null
if [ $? != "0" ]; then
  exit 1
fi
echo " done."

# result in "$NAME.vcd"
cd $OLDDIR
