.TH QucsTranscalc "1" "April 2005" "Debian/GNU Linux" "User Commands"
.SH NAME
QucsTranscalc \- A transmission line calculator.
.SH SYNOPSIS
.B qucstrans
[\fIOPTION\fR] ...
.SH DESCRIPTION

\fBQucs\fR is an integrated circuit simulator which means you are able
to setup a circuit with a graphical user interface (GUI) and simulate
the large-signal, small-signal and noise behaviour of the circuit.
After that simulation has finished you can view the simulation results
on a presentation page or window.

The software aims to support all kinds of circuit simulation types,
e.g. DC, AC, S-parameter, harmonic balance analysis, noise analysis,
etc.

\fBQucsTranscalc\fR is the transmission line tool used by Qucs.  The
application was somewhat inspired by \fBtranscalc\fR by Claudio
Girardi and Gopal Narayanan.  It is based on transcalc's latest CVS
version with some minor fixes incorporated.  The GUI has been ported
from the GIMP toolkit (GTK) to Qt.

It is an analysis and synthesis tool for calculating the electrical
and physical properties of different kinds of RF and microwave
transmission lines.

For each type of transmission line, using dialog boxes, the user can
enter values for the various parameters, and either calculate its
electrical properties, or use the given electrical requirements to
synthesize physical parameters of the required transmission line.

Available transmission lines are: Microstrip, Rectangular Waveguide,
Coaxial Line, Coplanar and Coupled Microstrips.

.SH AVAILABILITY
The latest version of Qucs can always be obtained from
\fBwww.sourceforge.net\fR or \fBwww.freshmeat.net\fR
.SH "REPORTING BUGS"
Known bugs are documented within the BUGS file.  Report bugs to
<qucs-bugs@lists.sourceforge.net>.
.SH COPYRIGHT
Copyright \(co 2005 Stefan Jahn <stefan@lkcc.org>
.PP
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH AUTHORS
Written by Gopal Narayanan <gopal@astro.umass.edu>, Claudio Girardi
<claudio.girardi@ieee.org>, Michael Margraf
<michael.margraf@alumni.tu-berlin.de> and Stefan Jahn
<stefan@lkcc.org>.
